### ISSUE TITLE
refactor intros/credits

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#101]
- [ ] own credit types
- [ ] merge `credits.xml` and `intros.xml`
- [x] allow to edit credits times

**Comment by AbandonedCart** [comment]
The repo seems to have gotten pretty destroyed. Not sure what happened, but I'm going to keep my fork for 10.8 if you want to make this one 10.9 and not worry about trying to keep it separate.

**Comment by jumoog** [comment]
i just squashed some commits together. The repo looks okay for me

**Comment by AbandonedCart** [comment]
Oh okay. It looked like it had gotten force pushed with half new and half old stuff

**Comment by jumoog** [comment]
Why you can't use Jellyfin 10.9? You dont use the Docker image?

**Comment by AbandonedCart** [comment]
I have two Macs and a ROG Ally. The Mac with good internet is locked to 10.14 for Photoshop, The Mac with 12 has terrible internet. The Ally doesn't have the storage space

**Comment by AbandonedCart** [comment]
Docker is junk on Mac

**Comment by jumoog** [comment]
Yes, I know the pain. I rented a cheap server and can access Jellyfin on the go.

**Comment by AbandonedCart** [comment]
It would probably be good to make 10.9 the master branch and make 10.8 the 10.8 since usually the current is what you'd expect to be master

**Comment by jumoog** [comment]
Yes that was my plan.

**Comment by AbandonedCart** [comment]
I was looking at the manifest and it seems like 10.9 will install if you have 10.9 and anything less will install what is the master branch right now. Wouldn't that make it possible to have a 10.8 branch and a 10.9 branch with master more or less just being a shared manifest?

**Comment by AbandonedCart** [comment]
Since the 10.9 release effectively installs the 10.9 version, I fixed the structure so the 10.9 branch is now master and 10.8 is now the secondary branch. It was going to have to get done eventually and was already causing some confusion. The builds still get tagged as 10.8 and 10.9 to make them easy to tell apart.

**Comment by rlauuzo** [comment]
To ensure the correct version is installed on 10.9, should we consider bumping the version number up (e.g., 0.1.17) for the 10.9 release? This would allow to add v0.1.16.5 to the master manifest without it superseding the 10.9 version.

**Comment by jumoog** [comment]
> To ensure the correct version is installed on 10.9, should we consider bumping the version number up (e.g., 0.1.17) for the 10.9 release? This would allow to add v0.1.16.5 to the master manifest without it superseding the 10.9 version.

Thats a brillant idea!

**Comment by AbandonedCart** [comment]
On the master branch, only 10.9 releases should be added to the manifest, but you might want to make it something more significant (ie. 0.2.01)

**Comment by AbandonedCart** [comment]
The builders are fixed now. I forgot that they used the full tag in the download link.

One thing that still needs to be done is bringing the 10.8 changes into 10.9.

**Comment by rlauuzo** [comment]
If we remove 10.8 releases from the master branch manifest, users on 10.8 will not receive updates unless they manually switch to the 10.8 branch. Leaving it in should be ok, as users on 10.8 can only install plugins compatible with target API 10.8. For users on 10.9, they will automatically receive the version with the higher version number?

**Comment by AbandonedCart** [comment]
> That's incorrect. Releases for 10.9 don't appear in 10.8; however, releases for 10.8 do appear in 10.9.

Care to explain how my server is 10.8 and I awoke to an unsupported error because the 10.9 plugin installed? I'm not speculation on how it should work. I'm telling you what happened.

**Comment by AbandonedCart** [comment]
Should be able to turn off that automatic CodeQL now. I added a yml one that's compatible with 10.9

**Comment by rlauuzo** [comment]
I'm noticing an issue with the Entrypoint on version 10.9. In 10.8, the log entry 'ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Running startup enqueue' appears on start, but it's missing in 10.9. Is Entrypoint not working?

**Comment by AbandonedCart** [comment]
GitHub is semi broken at the moment.

**Comment by AbandonedCart** [comment]
[![CodeQL](https://github.com/RepoDevil/intro-skipper/actions/workflows/codeql.yml/badge.svg)](https://github.com/RepoDevil/intro-skipper/actions/workflows/codeql.yml)

**Comment by jumoog** [comment]
> I don't know if you're aware of this, Jellyfin (10.10) will have media segments API. Discussion: [jellyfin/jellyfin-meta#30](https://github.com/jellyfin/jellyfin-meta/discussions/30) PR: [jellyfin/jellyfin#12345](https://github.com/jellyfin/jellyfin/pull/12345)

yes i'm aware

**Comment by AbandonedCart** [comment]
Seems like it took almost quadruple the work to do just the API as the entire plugin, doesn't it?
