### ISSUE TITLE
[Bug]: Skip button not displayed

### ISSUE THREAD

**Issue by hanshaoji** [jumoog/intro-skipper#104]
### Describe the bug

I'm using nyanmisaka/jellyfin,"Automatically skip intros" works fine,but “Show skip intro button" not working.

### Jellyfin installation method

Docker

### Container image and tag

nyanmisaka/jellyfin:latest,intro skipper 0.1.16.4

### Operating System

Synology DSM 7.21

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+ccb3bbc6835f
* Queue contents: 2747 episodes, 198 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by phyzical** [comment]
i think im getting this too

```
2024-04-03 09:17:51.985	
[18:17:51] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
```

**Comment by rlauu** [comment]
> i think im getting this too
> 
> ```
> 2024-04-03 09:17:51.985	
> [18:17:51] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
> ```
> 
> just to be clear i run dockerso i don't even have access to this file

If you're running the linuxserver/jellyfin image, you can use a custom script [https://docs.linuxserver.io/general/container-customization/#custom-scripts](https://docs.linuxserver.io/general/container-customization/#custom-scripts) and change ownership to abc
```
#!/bin/bash

chown abc /usr/share/jellyfin/web/index.html
```

**Comment by phyzical** [comment]
thx that seemed to sort it

**Comment by jumoog** [comment]
Thank you @rlauu

**Comment by hanshaoji** [comment]
> > i think im getting this too
> > ```
> > 2024-04-03 09:17:51.985	
> > [18:17:51] [ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > just to be clear i run dockerso i don't even have access to this file
> 
> If you're running the linuxserver/jellyfin image, you can use a custom script https://docs.linuxserver.io/general/container-customization/#custom-scripts and change ownership to abc
> 
> ```
> #!/bin/bash
> 
> chown abc /usr/share/jellyfin/web/index.html
> ```

I'm running the nyanmisaka/jellyfin image,
```
<script src="configurationpage?name=skip-intro-button.js"></script>
```
has been injected to index.html,but it's not working.

**Comment by AbandonedCart** [comment]
Is the button enabled in the plugin settings?

**Comment by hanshaoji** [comment]
> Is the button enabled in the plugin settings?

Yes,"Show skip intro button" is checked.

**Comment by ramonskie** [comment]
the custom chown script fixed it for me as well

**Comment by Cheffbenny** [comment]
Just adding this to help others.

I am running a windows server, and adding  <script src="configurationpage?name=skip-intro-button.js"></script> into the Jellyfin-web/index.html before the </body> fixed the issue of the skip intro button not showing for me.

This is based on the installation instructions given, you will need to update the the source if the location differs.

**Comment by AbandonedCart** [comment]
You should be able to fix the permissions on Windows much easier than Docker.

**Comment by jumoog** [comment]
> Just adding this to help others.
> 
> I am running a windows server, and adding <script src="configurationpage?name=skip-intro-button.js"></script> into the Jellyfin-web/index.html before the fixed the issue of the skip intro button not showing for me.
> 
> This is based on the installation instructions given, you will need to update the the source if the location differs.

Do you use Docker Desktop with WSL2?

**Comment by Cheffbenny** [comment]
> Do you use Docker Desktop with WSL2?

No, just the base windows server installation. I was struggling to find a fix given the permissions where correct and plugin was installed and scanned successfully, I looked to the index.html (incase the plugin was working but not showing) and this thread was the only one I found with a reference to the script in html format.
I was wanting to avoid using the original modified web interface from confused polar bear.

Working well on the base web interface.

Also shows on android mobile app (using the web player client settings), however when skipping to a different time or using the button that now shows it just resets to 0:00. - This is just feedback and doesn't affect using integrated player or external player which work fine but obviously doesn't pull plugins over, though they are designed for mobile use anyway.

**Comment by AbandonedCart** [comment]
For unraid:

"Add another Path, Port, Variable, Label or Device"
@jumoog - #104

![image thumb png e0062b1e664f0d6c1f8c3bfd0a2c8435](https://github.com/jumoog/intro-skipper/assets/5268791/9c3b408f-0085-4cdc-9d0d-a3b04f9af5cd)

`/mnt/user/appdata/custom-scripts/` is the location where the custom script is located in your filesystem.

**Comment by jackblk** [comment]
If you're using official 10.9.0 jellyfin docker image it is in `/jellyfin/jellyfin-web/index.html`

**Comment by Cloud9Developer** [comment]
I'm getting this error as well. Tried cloning the entire jellyfin-web and mounting it locally (intro button code got added after this), as well as the `docker exec` method above.. Both fails to show the button.

Running docker, official 10.9.1 image, chromium for the web player

**Comment by jackblk** [comment]
> I'm getting this error as well. Tried cloning the entire jellyfin-web and mounting it locally (intro button code got added after this), as well as the `docker exec` method above (code was injected here as well).. Both fails to show the button.
> 
> Running docker, official 10.9.1 image, chromium for the web player

@Cloud9Developer you need to run the command in my comment right after you start the jellyfin container, so the plugin can patch the file. Monitor the jellyfin container log, you should see the progress like this:

* Jellyfin start (probably using `docker compose up -d`)
* Patch using `docker exec` right away. I'm using Makefile for the deployment, so after my compose starts, it runs this command right after that
* Intro Skipper will now try to patch the file

I think that you might try to fix the permission AFTER the plugin's patching. In that case, the plugin should log that it fails to patch because it has no permission.

**Comment by Cloud9Developer** [comment]
hi @jackblk , Thanks for the reply. I actually have a script to do `docker run ... && docker exec ...` 

I did monitor it and it said it modified the index.html. I even confirmed the change is there by exec into the container and inspecting the file myself.

**Comment by AbandonedCart** [comment]
Do you have the button enabled and has the item you are testing it on completed scanning?

**Comment by Cloud9Developer** [comment]
Button is enabled in the settings, and I have completed scanning (confirmed with auto skip)

**Comment by AbandonedCart** [comment]
```
[2024-05-13 22:58:15.788 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "ConfusedPolarBear.Plugin.IntroSkipper, Version=0.2.0.3, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Intro Skipper_0.2.0.3/ConfusedPolarBear.Plugin.IntroSkipper.dll"
```
Well, the plugin loads
```
[2024-05-13 22:58:19.553 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Skip button already added
[2024-05-13 22:58:19.672 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Intro Skipper" "0.2.0.3"
```
It's finding the script
```
[2024-05-13 22:58:19.931 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Running startup enqueue
[2024-05-13 22:58:19.932 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Analysis settings have been changed to: 35% / 10m and a minimum of 15s
[2024-05-13 22:58:20.066 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Collections"
[2024-05-13 22:58:20.077 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Anime"
[2024-05-13 22:58:20.413 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Cartoons"
[2024-05-13 22:58:20.416 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Shows"
[2024-05-13 22:58:20.429 -05:00] [INF] [1] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Movies"
```
and it's loading your settings

**Comment by Cloud9Developer** [comment]
Agreed, which is why, like the name of the original repo, I am a confused polar bear :sweat_smile:

**Comment by AbandonedCart** [comment]
Usually that means the issue isn't in the plugin, but the UI.

**Comment by Cloud9Developer** [comment]
I see others have it working on 10.9.0 above, wonder if it's because of the new 10.9.1 release?

**Comment by AbandonedCart** [comment]
Couldn't say. I'm one of the people that got dropped by the 10.9 update.

The opacity of the button is set to a default of 0, but then the intro / credit segment triggers making it visible to animate it back to hidden. It's possible that if the triggers aren't firing somewhere, the opacity remains at 0. The only way to really confirm that would be to know where the button should appear and see if it's possible to skip by clicking there or setting the opacity back to 1 and seeing if clicking it during an intro or credit section works.

**Comment by AbandonedCart** [comment]
https://github.com/jumoog/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js#L23C7-L30C49

It's also possible the API changes, since we use an arbitrary path segment count

**Comment by Cloud9Developer** [comment]
I tried changing the opacity just now, that's not it.

Ahh, yeah the API most likely changed. I noticed (and made a pull request) for something similar in this repo

**Comment by Cloud9Developer** [comment]
I just found this: 
![image](https://github.com/jumoog/intro-skipper/assets/32144556/6810ca05-cdad-49d5-8f25-05b4c52b29fb)

**Comment by Cloud9Developer** [comment]
Ahh, I just found this: 
![image](https://github.com/jumoog/intro-skipper/assets/32144556/b4b5c083-4012-4f68-8bcc-6eb3ae66a093)

**Comment by jumoog** [comment]
This is what happens when you do not have any values for this episode.

**Comment by Cloud9Developer** [comment]
@jumoog wouldn't the auto skip (when it's enabled) fail to skip though if that's the case?

**Comment by matt1432** [comment]
I'm also unable to see the skip button even though everything seems correct. I also saw that the opacity was set to 0 and tried changing it but it just instantly goes back to 0 after seeing it for a frame.

I'm on 10.9.1

**Comment by jackblk** [comment]
@Cloud9Developer I had issues when migrating to this new plugin too, might be related to your case.

Everything worked (patching), but the Skip button was not displayed. I checked the API called, the previous info for skipping was not valid anymore (probably incompatible with the new plugin?).

I erased every fingerprints and schedule a new task to generate everything again. It worked for me but it took hours.

**Comment by Cloud9Developer** [comment]
@jackblk yeah, I did that too last night. Erased through the plugin's settings page AND delete the folder in /cache. Started the scan last night, so will check later today when I get home to see if that resolved it. Will let you know once I'm able to confirm

**Comment by AbandonedCart** [comment]
We probably shouldn't be moving existing content to the cache if coming from the "original" plugin. Then again, we also can't retroactively add a better method to identify that the data did come from the previous one. This may end up just needing to be a note somewhere.

**Comment by Cloud9Developer** [comment]
I just got home to test if removing all fingerprints via plugin settings page and deleting all /cache/introskipper files, then rescanning worked. Nope, no luck.. Skip button still refuses to show up (but autoskip works when enabled) :/

**Comment by Cloud9Developer** [comment]
I found the issue!

It's in the inject.js, line 28:
`let id = path.split("/")[3];`

This fails if you have a context root/path set for jellyfin.

For example, if the path is `/myjellyfin/Items/1b0e9d8506ffde97177b336049b1f989/PlaybackInfo`

instead of getting '1b0e9d8506ffde97177b336049b1f989', it's getting 'Items', which is breaking the button from showing up.

**Comment by Cloud9Developer** [comment]
Working on a pr now to add logic for a context root (but if you have a better way to check for context root, by all means ignore my solution and implement that! :) )

**Comment by Cloud9Developer** [comment]
https://github.com/jumoog/intro-skipper/pull/165 should fix it. Tested it on my end, and works

**Comment by Aydanill** [comment]
How do you fix it on windows?

**Comment by AbandonedCart** [comment]
It would be the same fix, if it's the same issue. The issue is with the way the URL is read.

**Comment by jumoog** [comment]
its done

**Comment by Cloud9Developer** [comment]
Would you like me to go and clean it up with better methods later still? Or it's fine as is?

**Comment by AbandonedCart** [comment]
You shouldn't need it on the previous version. The issue was caused by the changes in the upgrade

**Comment by AbandonedCart** [comment]
Since we have all the scripts here, I’ve hidden everything else and locked it to keep that info easy to locate.

**Comment by AbandonedCart** [comment]
Find `index.html` in `C:\Program Files\Jellyfin\Server\jellyfin-web` and modify the permissions for your user to Full Control. Then restart Jellyfin.

_Originally posted by @rlauuzo in https://github.com/jumoog/intro-skipper/issues/210#issuecomment-2213255438_

**Comment by AbandonedCart** [comment]
Unpinning this since it will be part of the readme.
