### ISSUE TITLE
Help Wanted: "UnableToAddSkipButton"

### ISSUE THREAD

**Issue by GuardianWitch** [jumoog/intro-skipper#108]
### Describe the bug

I can't get the skip button to show. I installed it as described in the README. And when it didn't work I followed the Troubleshooting.  I verified the task ran at least once, I cleared my cache and reloaded the page, and because I run it in docker I nuked the container and it's settings and recreated it with the User lines commented out.  None of these have helped.  The show button option is checked.  I did make sure the plugin was working by trying to automatically skip intro and that worked. But I don't want to use that option.

I don't know where the Warning: "UnableToAddSkipButton" is coming from and rather than banging my head against my desk I thought I would ask.
(I am trying to get this to work on my test server before adding it to my main one, so having to nuke it and restart isn't a problem.)

### Jellyfin installation method

Docker

### Container image and tag

hotio/jellyfin:latest

### Operating System

Debian 12 Raspberry Pi

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 55 episodes, 5 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

**Comment by AbandonedCart** [comment]
Did any of https://github.com/jumoog/intro-skipper/issues/104 help?

**Comment by GuardianWitch** [comment]
No. I tried the script and it didn't work.

**Comment by phyzical** [comment]
@GuardianWitch when you boot jellyfin in the logs you should see why its failing as it loads the plugins, hopefully that will help narrow down the issue (for me it was permission related)

**Comment by rlauuzo** [comment]
Temporary Fix (After Each Update):

Open terminal.
Run the following command, replacing <container_name> with the actual name of your Jellyfin container:
`docker exec -d <container_name> chown hotio /usr/share/jellyfin/web/index.html`
restart the container.

Permanent Fix (Using Docker Compose):

Open your docker-compose.yml file.
Under the section for your Jellyfin container, add the following line:
`command: chown hotio /usr/share/jellyfin/web/index.html`
Save your changes and restart the container.

**Comment by GuardianWitch** [comment]
@rlauuzo THANK YOU!  I added the command to my compose file and it works!
