### ISSUE TITLE
[Bug]: Scanning triggered without notice

### ISSUE THREAD

**Issue by VampiricAlien** [jumoog/intro-skipper#112]
### Describe the bug

After have high CPU to see it was jellyfin but nothing was trancoding turns out the plugin is scanning without telling jellyfin what's going on.

There should be a notice on the dashboard and in tasks.

### Jellyfin installation method

Linux

### Operating System

Ubuntu

### Support Bundle

```shell
* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`
```

**Comment by AbandonedCart** [comment]
Do you have automatic scanning enabled in the plugin settings?

**Comment by AbandonedCart** [comment]
The plugin uses a cache to determine what needs to be scanned. That cache is established from the media you have previously analyzed. This means that if you have no cache and begin to automatically scan new items, all of them would be new to the cache. While it does respond to new items specifically, it also verifies that it has scanned everything else already for the sake of making sure none got missed. What we haven't determined, in relation to your primary issue, is whether or not it is **needlessly** scanning contents.

As for your issue about a notice, I will look into adding more notifications. At the same time, understand that it is going to slow the process down a bit and it is a completely optional feature that is only fired when you add or change items and when you update your library.

**Comment by AbandonedCart** [comment]
Whether it's scanning files already logged or not.

There are settings for that, yes.

**Comment by AbandonedCart** [comment]
Ironically, thread count is literally the description of a setting under Process Configuration.

**Comment by AbandonedCart** [comment]
That aside, I am trying to find where this information is listed for other Plugins, such as Jellyscrub. To the best of my knowledge, it appears in the web console, but we already post logging there. I don't see any other plugins with automatic response to media posting logging or notifications anywhere else. I also get the impression that if you have a season of 13 episodes and add that to your library, you'll be right back posting an issue about getting 13 rapid fire notifications. I think we'll leave the logging as is for now.

The other issue is one I am investigating. If I can find a leak where it is scanning more than it really should during the automatic process, action will be taken to resolve that.

**Comment by AbandonedCart** [comment]
Automatic scanning is cancelled by the scheduled tasks. I have a feeling the issue may be in event priority. A lot of people refresh their library after adding files and the automatic task for items added is the same for library refreshed. In turn, the library refresh gets appended as a separate scan after the items added. I'm verifying the changes now to prioritize library scan so it cancels one off files.

**Comment by AbandonedCart** [comment]
A lot of that is already implemented, which is why there is usually no need to worry about double scanning the same file. The question is why, in your case, that sounds like a fresh scan every time.

**Comment by jumoog** [comment]
> What is TwistedUmbrellaX?

His name on Github

**Comment by AbandonedCart** [comment]
For now, going with "can you give the latest build a try and see if that improves things?" would have been enough. You typically only link pull requests to issues when they are a work in progress, a known fix, or take more than an hour to merge.

**Comment by AbandonedCart** [comment]
That sounds like progress. The next iteration is #119, but I'm trying to make sure I don't end up filtering so much that items get overlooked

**Comment by AbandonedCart** [comment]
Did you happen to refresh the library by any chance?

**Comment by AbandonedCart** [comment]
I have a feeling you are describing the current setup. 

We have a full scan scheduled for midnight. This is something you can configure in the scheduled tasks. 

We have optional automatic scanning, which fires when files are added or modified or the library is refreshed. These can be toggled from the plugin settings.

Almost everything is optional and the default configuration won't work for everyone. I can't really consider it a bug if the defaults aren't a good fit, though.

**Comment by AbandonedCart** [comment]
The best advice I could give is to take a look through all of the options available and see if they allow the configuration you want. If there is an option missing that you need to accomplish that, we can look into adding that.

**Comment by boydaihungst** [comment]
I also have this problem. Full scan trigger every time run `scan for new and updated files` for a single show (recent for this becaise I need to rescan for sub after bazarr downloaded it), new episode downloaded. It's not rescan exactly the show, but all shows, over and over again. I did full scan before. It's should run incremental scan like the old intro-skipper.

I use the this latest merged build (https://github.com/jumoog/intro-skipper/actions/runs/8740310352) on jellyfin server 10.9.0

**Comment by AbandonedCart** [comment]
I don't think 10.9 has been updated with those changes yet. The current pull requests will supersede them.

**Comment by boydaihungst** [comment]
I disabled auto update plugins and replace .dll file with the one from action build. So it should be the latest, right?

**Comment by AbandonedCart** [comment]
It may not completely resolve the issue. 10.8 got a patch to stop the issue temporarily. 10.9 is being rewritten to not need the temporary patch, but the work is ongoing.

**Comment by boydaihungst** [comment]
Good to know 👍 For now I will have to disable this plugin.

**Comment by AbandonedCart** [comment]
You could just disable the auto scans. Those are what's running repeatedly.

**Comment by AbandonedCart** [comment]
I jumped the queue a bit and added the temporary patch. It will be in the latest master test build

**Comment by boydaihungst** [comment]
Many thanks. I will test it right away. One last question, my library have ~9000 episodes, should I disable cache fingerprint?

**Comment by AbandonedCart** [comment]
Definitely not. Cache makes it scan faster.

**Comment by boydaihungst** [comment]
I can confirmed that the bug is fixed. 

After run `detect intros and credits` in schedule tasks, only new or changed episodes are reanalyzed. Not test automatically scan yet. You guys did a really good job.
