### ISSUE TITLE
[Feature Request] Adjustable Credits detection time

### ISSUE THREAD

**Issue by BLACK4585** [jumoog/intro-skipper#115]
Currently, there are only options to adjust the max introduction time. The max 4 minutes length for credits is hard-coded. It would be nice to be able to adjust also this, since a few shows have longer credits, like the new Fallout series for example.

**Comment by AbandonedCart** [comment]
Credits detection works differently than intros. It primarily detects standard cues for credits, not necessarily a chunk of matching audio. Is this based on an actual issue you had or just the lack of an option?

**Comment by AbandonedCart** [comment]
Max time has been increased to 10 minutes until the options can all be added. Not sure it will have much impact, but it won't hurt anything.

**Comment by BLACK4585** [comment]
Yes makes sense, since the sound in the background of the credits are often different from episode to episode. 
Yes, I noticed it with the new Fallout series, it has slightly longer credits.

**Comment by BLACK4585** [comment]
Okay thank you very much! When I change options regarding the times and manually scan again, will it rescan all files? Also regarding this change now.

**Comment by AbandonedCart** [comment]
It may scan everything again, since the parameters are different. It will still have the cache of the fingerprints, though. They are separate from the timestamps.

**Comment by BLACK4585** [comment]
So it makes sense to delete everything in `/config/cache/introskipper/`?
Also could this be a feature for the future, re-scan everything?

**Comment by AbandonedCart** [comment]
It doesn't make sense to delete the cache unless you want to force a rescan because the physical files are using the same name, but the length has changed.  As for overriding the cache, It is already a feature.

**Comment by BLACK4585** [comment]
So just for my understanding, do I have to delete the cache in order to get the new timestamps/fingerprints? xD
And by overriding, do you mean `Regenerate EDL files during next scan`? Will this also override the cache when the `EDL Action` is set to `None`?
Sorry for the questions, I just want to be sure when the update with the new time is is released.

**Comment by AbandonedCart** [comment]
Fingerprints and timestamps are not interchangeable. Fingerprints are the Chromaprint marks for matching audio. They are cached. Timestamps are the time markers that are determined as the beginning and ending of credits or intros. They take the minimum and maximum into account, but are overwritten by a scan.

EDL is a completely separate feature where the information normally provided in the plugin API is written to a file compatible with other media players. Enabling these allows you to use the same library with a different player and take advantage of the plugin's analysis there. If you change duration and such, you would want to overwrite these.

The cache option is under Process Configuration and is enabled by default. It writes the CHromaprint fingerprints to a cached file to speed up future scans, especially if you are changing duration and other things that use the same file with different user settings.

That said, It doesn't make sense to delete the cache unless you replace files with ones that are named the same, but have a different length than the ones they are replacing.
