### ISSUE TITLE
Android does not show the button

### ISSUE THREAD

**Issue by CarlosThor** [jumoog/intro-skipper#124]
Hello, sorry, but I'm fairly new here when it comes to asking questions or problems, and I'm not sure if this is the appropriate place.

My question is that after implementation, I can't get it to work on my Android phone; it doesn't show the button (skip introduction and skip credits).

Is there something specific that needs to be done for it to work on Android or Android TV? I'm interested in both.

I'm working with docker-compose. If there's any example of why it might not be working, I would appreciate it.

Previously, I did use the old version of this plugin, but I installed /jellyfin/jellyfin-web:ro, which was what made it work, and from the tests I've done, this shouldn't appear now.

Thank you very much.

**Comment by jumoog** [comment]
This plugin is not supported by the official Android/Android TV app. But you can set the **Automatically skip intros** Option and the Server will handle it for you.

**Comment by jumoog** [comment]
This plugin is not supported by the official Android/Android TV application. However, you can set the **Automatically skip intros** option and the server will do it for you.

**Comment by CarlosThor** [comment]
Okay, thank you very much, I will be aware of if any updates come out with these, thanks again

**Comment by rlauuzo** [comment]
@CarlosThor Try using the "web player" option in the client settings
