### ISSUE TITLE
[Feature Request]: Show credit information in "Manage Fingerprints" page.

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#129]
### Describe the bug

I noticed that credits were not scanned/being skipped for a show I have so I wanted to check on the plugin page, but the timestamps for the credits are not listed there. It would be helpful information to have access to and/or edit.

### Jellyfin installation method

apt

### Operating System

Ubuntu 20.04

### Support Bundle

```shell
* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+c2727ea4e482
* Queue contents: 19349 episodes, 1243 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Could you please install the preview release to see if it resolves the problem? There is a bug in the current version that causes chromaprint calculations to fail for credits when an intro timestamp is already present. https://github.com/jumoog/intro-skipper/releases/tag/10.8%2Fpreview

**Comment by d8f6** [comment]
Okay, I changed the ownership of that file and moved it to the plugin directory. Now, the detect credits is taking a long time (which is a good sign). I suspect this was the fix, but won't know until it finishes (probably be a few hours at least). Will report back after.

**Comment by d8f6** [comment]
@rlauuzo So, that new dll you linked did cause the credits to get picked up, but on the show I tested the timing is off about 50 seconds (starts ~50-55 seconds too early). Also, intro only skipped first 30 seconds instead of the entire intro. I tried deleting and rescanning but got the same results. I looked through the settings and nothing is changed on my end. Not sure if this is a regression or not. I replaced the dll with the old one and rescanned and that fixed the intros, but after rescanning the credits it is using the old (wrong) value (assuming this is because it cannot scan for a new one with the older version). So, I deleted the cache again and rescanned the intro only, but the same wrong time for the credits persist unfortunately. I seem to be worse off than when I started. Guess I'll just have to turn off auto skip for credits and wait until the next stable update comes out. Thanks for the help anyways though.

**Comment by rlauuzo** [comment]
I believe the 55-second offset is directly caused by the maximum credit length increasing from 240 to 300 seconds in the preview version. This change likely explains why you needed to perform a full rescan. @AbandonedCart
 
If you're still using the preview version, try doing this:
- Delete the existing season timestamps in the plugin settings.
- Restart Jellyfin (this is important to apply the changes).
- Start a new scan.

That's an odd issue with the 30-second intro detection. I haven't encountered that, and I'm not aware of any recent changes to the detection logic. Could you provide some more details?

**Comment by d8f6** [comment]
Oh, I did not restart jellyfin. I guess I should have because I was replacing a plugin file? I'll run some more tests tomorrow and see if I cannot figure this out. Yeah, the 30 second thing was weird. Not sure what other details I could provide. The log files usually just say scanning show etc... If there is something that still needs to be fixed I don't mind waiting for the next stable release. I will restest tomorrow though and report back.

**Comment by jumoog** [comment]
> Oh, I did not restart jellyfin. I guess I should have because I was replacing a plugin file?
Yes, plugins are loaded on startup.

**Comment by AbandonedCart** [comment]
> I believe the 55-second offset is directly caused by the maximum credit length increasing from 240 to 300 seconds in the preview version. This change likely explains why you needed to perform a full rescan.

But then by that theory, you can't ever change the user settings.  If it was a 60 second offset, I would be more convinced. It's only the maximum duration, though.

**Comment by rlauuzo** [comment]
I've also experienced the shift. For me credits for episodes added before the maximum duration change were shifted by exactly 60 seconds. Aren't chromaprints for credits are calculated relative to (runtime - maximum credit length).

**Comment by AbandonedCart** [comment]
It only changes where the analysis starts, but chromaprints don't use it. It's black frame.

**Comment by rlauuzo** [comment]
The issue is that credit chromaprints are created relative to the CreditsFingerprintStart point. When the maximum credit length changes, this point shifts, but the cached chromaprints remain tied to the old starting point, causing the misalignment.

**Comment by AbandonedCart** [comment]
So the ability for the user to change the value is broken, since the premise for that change was that credits were being ignored for newer shows.

**Comment by jumoog** [comment]
>  the cached chromaprints remain tied to the old starting point, causing the misalignment.

I'm not sure if this is a feature or a bug. But recreating the whole cache is very expensive.

**Comment by AbandonedCart** [comment]
The chromaprints themselves aren't tied to anything. It's the resulting calculation.

**Comment by jumoog** [comment]
I had the idea of something like Youtube sponsorBlock. But for Jellyfin. I see some legal problems 😂

**Comment by AbandonedCart** [comment]
Either the max duration needs to be 10 minutes (the absolute longest credits currently known are around 9.5) and not be an option or the logic to setting them needs to be reworked to adjust. As is, though, it sounds like users will break all their timings trying to change anything.

**Comment by rlauuzo** [comment]
I can't test it since I don't have access to shows with credits long enough. However, wouldn't this method work better for longer credits, when using black frames? https://github.com/jumoog/intro-skipper/pull/132

**Comment by d8f6** [comment]
I was estimating 50-55 seconds before in my test, so it very well could be 60 seconds as stated by @rlauuzo I am not sure. I did not actually change any settings in the gui at all, I just replaced the dll file with the one that was provided. If it helps, my show credits are only usually around 90 seconds for the most part.

Since my entire cache was rescanned, it seems like I am going to have to delete it all and rebuild it. Going to wait for the next update to do this instead of retesting now. Not sure if I need to go in and delete the files or if the "Erase all end credits timestamps (globally)" option will do the trick (I guess we'll see).  I could just delete the files that end in -credits and then delete the credits.xml file while the jellfin daemon is stopped (are we still moving towards a single xml file or is that not a thing anymore?)? Anyway, sound like I need to hold tight here and do nothing for now while things get sorted out. Thanks for the additional testing/help everybody.

**Comment by rlauuzo** [comment]
> I was estimating 50-55 seconds before in my test, so it very well could be 60 seconds as stated by @rlauuzo I am not sure. I did not actually change any settings in the gui at all, I just replaced the dll file with the one that was provided. If it helps, my show credits are only usually around 90 seconds for the most part.
> 
> Since my entire cache was rescanned, it seems like I am going to have to delete it all and rebuild it. Going to wait for the next update to do this instead of retesting now. Not sure if I need to go in and delete the files or if the "Erase all end credits timestamps (globally)" option will do the trick (I guess we'll see). I could just delete the files that end in -credits and then delete the credits.xml file while the jellfin daemon is stopped (are we still moving towards a single xml file or is that not a thing anymore?)? Anyway, sound like I need to hold tight here and do nothing for now while things get sorted out. Thanks for the additional testing/help everybody.

If you're still using the preview version, you might try to change the maximum credits duration to 240.

**Comment by d8f6** [comment]
@rlauuzo No, I completely removed the plugin and plugin folder and reinstalled from the repo and then disabled auto skip for credits. Re-scanning takes me like 8-10 hours and I cannot test for the next few days anyway as I have a couple other projects to finish. So, it was a scan duration issue?

**Comment by AbandonedCart** [comment]
Any credits over 4 minutes won't be detected at 240. That's the catch.

**Comment by d8f6** [comment]
Before, for credits near the end of the episode, it skipped the credits all the way to the end of the episode so I can just play the next one. I hope that is still a thing with the duration changes. I was going to look at what my values are but since I am back on the stable version I do not think I have these options (Just the "Modify Intro Perameters"). I did not see them anyway. For credits at the very end of an episode it seems to me that some credits will exceed 4 minutes when you include both the credit sequence and the produciton information etc... Seems like a pretty big catch to me just saying.

**Comment by rlauuzo** [comment]
> I can't test it since I don't have access to shows with credits long enough. However, wouldn't this method work better for longer credits, when using black frames? #132

I did some testing. I changed the maximum credits duration to 3 minutes, and it successfully detected the credits in the new Fallout show, which are 5 minutes long. It appears to be working.

**Comment by AbandonedCart** [comment]
That also means the user setting is essentially meaningless.

**Comment by rlauuzo** [comment]
Is that problematic? It's still utilized for chromaprints and chapters. However, considering chapters are essentially free, perhaps the maximum duration for them should also be increased.

**Comment by boydaihungst** [comment]
Yes. I really need this to manually adjust credit timestamps. Some anime show doesn't recognize the right credit timestamp. e.g: Shangri-La Frontier.

**Comment by rlauuzo** [comment]
I suspect the issue is with chapter markers. Some anime label the outro scene as "credits start" and the epilogue as "credits end." This likely causes the chapter analyzer to mistakenly identify the epilogue as the credits.

**Comment by boydaihungst** [comment]
> I suspect the issue is with chapter markers. Some anime label the outro scene as "credits start" and the epilogue as "credits end". This likely causes the chapter analyzer to mistakenly identify the epilogue as the credits.

The file I tested is only have 4 chapter: chapter , chapter 2, chapter 3 and chapter 4.

**Comment by rlauuzo** [comment]
I downloaded Shangri-La Frontier, and here's how the chapter markers are formatted:
```
00:00:00.000                   : ja:Prologue
00:00:41.000                   : ja:Opening
00:02:11.000                   : ja:Episode
00:21:54.000                   : ja:Credits Start
00:23:24.000                   : ja:Credits End
```

**Comment by boydaihungst** [comment]
https://nyaa.land/view/1797128
I downloaded subsplease S1 batch.

**Comment by rlauuzo** [comment]
I checked the subsplease files and they don't have chapter markers. The issue is likely that the plugin currently scans only the last 4 minutes, and the outro begins earlier.

**Comment by boydaihungst** [comment]
Anyway, the chapter doesn't need to detect credit/outro. I have checked another show, which also doesn't have chapter markers, and the credit was detected without any problem. The Shangri-La show, please check episode 12 season 1 (there are more episodes in this series have this problem). The outro starts at ~20:09 but the skip button is shown at ~19:06. If I click Skip button, it'll go through half of the credit though. I already remove timestamp for this season, restart jellyfin and rescan outro/intro.
![Screenshot_20240501-154629_Firefox_Nightly](https://github.com/jumoog/intro-skipper/assets/38396158/4bcbc4a3-576a-48c1-9f41-66c3e3013111)
![Screenshot_20240501-154026_Firefox_Nightly](https://github.com/jumoog/intro-skipper/assets/38396158/47ceb6a1-6afe-450b-b0d0-dda55732991a)

**Comment by rlauuzo** [comment]
Are you using the preview version?

**Comment by boydaihungst** [comment]
Yup. 10.9.0 build version 2024042905. Also, use the latest preview plugin.

**Comment by AbandonedCart** [comment]
> I suspect the issue is with chapter markers. Some anime label the outro scene as "credits start" and the epilogue as "credits end". This likely causes the chapter analyzer to mistakenly identify the epilogue as the credits.

I accounted for that. If there are two sets of credits or intros, it favors the last intro and the first credits.

**Comment by rlauuzo** [comment]
Would it be possible to blacklist entries like 'Credits End'?

**Comment by rlauuzo** [comment]
> I accounted for that. If there are two sets of credits or intros, it favors the last intro and the first credits.

It seems than the credits overlap check might be missing. Would this be a suitable solution: https://github.com/rlauuzo/intro-skipper/commit/e9996a51b67e6213b6cbfee79676edb4b9a7451f

**Comment by AbandonedCart** [comment]
It's counting down from the end and the last chapter is a fake. The end value should be the beginning of the next chapter. That sets the end value to the beginning of the previous chapter. If your credits started at 2 minutes and ran for 30 seconds, you'd end up with a start time of 2 minutes and an end time of 1.5 minutes.

**Comment by AbandonedCart** [comment]
Might be better to use "previous" as the previous chapter and chapters[i + 1] directly in the tick.

**Comment by rlauuzo** [comment]
How about extending the Maximum Duration for credits in the chapters analyzer? I've already set the Maximum Duration to 2 * MaximumCreditsDuration in the blackframe analyzer, but perhaps setting it to 10 minutes / 25% of the total video length, similar to what we do for intros, would be better. Additionally, we might want to have a separate MaximumCreditsDuration specifically for chromaprinting credits.

**Comment by AbandonedCart** [comment]
Makes sense. Originally, the bump to 5 minutes was because I didn't want 10 to create an excessive amount of lag, but that shouldn't be a concern now.

**Comment by d8f6** [comment]
I could easily see a credit sequence extending beyond 5 minutes for longer shows. The percentage idea "25% of the total video length" similar to the intro scanning seems like it makes the most sense to me. A lot of content probably will not have chapter markers for this sort of thing. Any intial extra scanning overhead seems worth it to me.

**Comment by AbandonedCart** [comment]
Wasn't it one of your issues that it was scanning too much and taking entirely too long?

**Comment by d8f6** [comment]
No, it was that my scan started over from the beginning completely for some reason. After the initial scan, everything worked normally afterwards. Cache related somehow according to that other thread? Assuming we are writing about this thread?:   https://github.com/jumoog/intro-skipper/issues/93

It started working normally after the first scan, so I am not sure what the issue was. Could have just been a normal part of updating the plugin? I am not entirely sure.
```
That aside, it's not a decision of one or the other.
```
This is way over my head as I do not completely understand how the code works.

**Comment by AbandonedCart** [comment]
> This is way over my head as I do not completely understand how the code works.

I was responding to your opinion on how it should be handled.

**Comment by d8f6** [comment]
Oh, right. I just noticed that in my library there are some credits that exceed 5 minutes in total. I am pretty sure that I've never seen any credits over 10 minutes personally. Usually the shows are longer in length though (> 40-50 min). That's why I though the 10min/25% comment above by @rlauuzo above made sense to me. I should probably just save my commentary as it does not seem to be useful in the context of this thread I guess.

**Comment by AbandonedCart** [comment]
Do whatever you please, but kindly accept my apology for disregarding it.

**Comment by 000junichi** [comment]
@jumoog Are there plans to manage fingerprints for ending credits?

**Comment by AbandonedCart** [comment]
I started to mark everything after where this took a sharp left into being about the credits detection being inconsistent, inaccurate, or whatever other *in* words, but that's basically the whole issue. Since the other issue was addressed, though, we can probably go back to this one being about the editor.

**Comment by jumoog** [comment]
> @jumoog Are there plans to manage fingerprints for ending credits?

Stop mentioning me. It is just annoying. I see all the comments anyway.

**Comment by jumoog** [comment]
will be added in #223
