### ISSUE TITLE
[Discussion]: Subdirectories for chromaprints 

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#131]
### Describe the bug

I am thinking that eventually subdirectories will/or should be created for the chromaprint files in the same way that jellyfin stores library data or ccache stores files. For example if I do an "ls /var/lib/jellyfin/metadata/library/ " I get an output like this:
```
00/  09/  12/  1b/  24/  2d/  36/  3f/  48/  51/  5a/  63/  6c/  75/  7e/  87/  90/  99/  a2/  ab/  b4/  bd/  c6/  cf/  d8/  e1/  ea/  f3/  fc/
01/  0a/  13/  1c/  25/  2e/  37/  40/  49/  52/  5b/  64/  6d/  76/  7f/  88/  91/  9a/  a3/  ac/  b5/  be/  c7/  d0/  d9/  e2/  eb/  f4/  fd/
02/  0b/  14/  1d/  26/  2f/  38/  41/  4a/  53/  5c/  65/  6e/  77/  80/  89/  92/  9b/  a4/  ad/  b6/  bf/  c8/  d1/  da/  e3/  ec/  f5/  fe/
03/  0c/  15/  1e/  27/  30/  39/  42/  4b/  54/  5d/  66/  6f/  78/  81/  8a/  93/  9c/  a5/  ae/  b7/  c0/  c9/  d2/  db/  e4/  ed/  f6/  ff/
04/  0d/  16/  1f/  28/  31/  3a/  43/  4c/  55/  5e/  67/  70/  79/  82/  8b/  94/  9d/  a6/  af/  b8/  c1/  ca/  d3/  dc/  e5/  ee/  f7/
05/  0e/  17/  20/  29/  32/  3b/  44/  4d/  56/  5f/  68/  71/  7a/  83/  8c/  95/  9e/  a7/  b0/  b9/  c2/  cb/  d4/  dd/  e6/  ef/  f8/
06/  0f/  18/  21/  2a/  33/  3c/  45/  4e/  57/  60/  69/  72/  7b/  84/  8d/  96/  9f/  a8/  b1/  ba/  c3/  cc/  d5/  de/  e7/  f0/  f9/
07/  10/  19/  22/  2b/  34/  3d/  46/  4f/  58/  61/  6a/  73/  7c/  85/  8e/  97/  a0/  a9/  b2/  bb/  c4/  cd/  d6/  df/  e8/  f1/  fa/
08/  11/  1a/  23/  2c/  35/  3e/  47/  50/  59/  62/  6b/  74/  7d/  86/  8f/  98/  a1/  aa/  b3/  bc/  c5/  ce/  d7/  e0/  e9/  f2/  fb/
```
Where each folder hold around 100 files or so. 

With the current implementation if I do a "ls chromaprints | wc -l" the value I get is 81222. I suspect that having so many files stored in one directory will create some type of issue in the future (I do not understand the issue personally as I am not a programmer, but I believe there is a reason things are normally done using the subdirectory structure). When I look at the files in the chromaprints directory they are already structured in the same way (currently from 00* to ff* on my system). This does not seem to be an issue yet, but as this number will probably increase more and more over time for those with large libraries I feel that this change should eventually be considered. The potential downside to changing the structure is that libraries may have to be rescanned in the future, but I was wondering if the devs here had any thoughts about this. Perhaps for the 10.9 branch this is something that can be considered?  Okay, thanks.

### Jellyfin installation method

apt

### Operating System

Ubuntu 20.04

### Support Bundle

```shell
* Jellyfin version: 10.8.13
* Plugin version: 0.1.17+26db24d187ed
* Queue contents: 19349 episodes, 1243 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
```


### Jellyfin logs

_No response_

**Comment by d8f6** [comment]
Edit: I am unsure of how to remove the "bug" label, as this is not a current bug in terms of functionality. Just wanted to point that out for any other users reading this thread.

**Comment by AbandonedCart** [comment]
So there's no issue and you're not sure how there would be an issue, but propose we radically change the entire core of how the scan process is designed because you suspect there may eventually be the possibility of an unknown bug?

Think maybe you are just searching for something to report?

**Comment by d8f6** [comment]
Well, besides broken shell expansion and possible performance degredation (this may be dependent on filesystem type), this should not affect the functionality of the program in any way. To answer your two questions though: No. This is not a feature request or a bug that I am reporting. Also, my proposal was that "this change should eventually be considered" (I still think this). Not that this change be worked on or implemented immediately. It is just something that I thought should be discussed and/or considered by people who know more about programming than I do. That is why I put "[Discussion]" in the subject header.

Surely there is a reason why all other programs that create a large number of files use a subdirectory structure? File iteration times? Inodes?  Again, I am not a programmer and this is not my field of expertise. I started this post hoping that an intelligent conversation could be had about the structure being used between the programmers working on this project, not necessarily with me. I can assure you that it was not meant to be an topic that affected the emotional state of the reader. Maybe I'm wrong and none of this matters in the context of performance or other filesystem related issues. I don't actually know (that's part of why I made this post). It is just something I noticed that was different about how this program functions as opposed to other programs that also create very large numbers of files, so I wanted to bring it up in case it matters. I hope that clears up my original intentions. If, for some reason, you do not think this is even worth discussing I can simply close this thread so that it does not appear in the open issues section if you would like.

**Comment by AbandonedCart** [comment]
Since you asked, the reason all files are kept in the same folder is how they are made and what they contain. They are made using ffmpeg with a very minimal set of arguments and contain a list of numbers. If we were to iterate through the directory, it would be a lot. If we were to attempt to find an unknown file among them, it would be a lot. We write to the files and then use them by name.

Ideally, everything would be written to a database contained in a single file. That's why the part where we do search and do iterate is an xml. The cache files are meant to save time on scans. It sounds like this all traces back to tampering with them. 

But say we decide to invest the time dividing the files up, tracking where they're placed, and all that stuff. How to we determine the folder? Season? What if you placed an episode in the wrong one? Sure, we can use the scraper season assignment, but what about when you change scrapers? That's probably not going to work. Alright, so we do alphabetical. A folder for every prefix. We get the episode id, get the prefix, check for a folder, create the folder, then we can write the file like before. When it's time to use it, we have to determine the episode id again, get the prefix again, check for that folder again, open that folder again, then we can finally do what we were doing before to read the file. Seems like a lot of extra steps to be facilitate manually tampering with cache files.

**Comment by d8f6** [comment]
Oh, I see. So, instead of an improvement in performance, we would see a decrease in performance due to all the extra steps required for the checks? Well, nobody wants a slower scan (I certainly don't). I thought about the database idea too, but that seems like it may not be possible or be extremely difficult to do in a plugin (assuming more depencies on the host would be required for it to function at all?). Okay, well if it doesn't make sense (which it doesn't seem to at this stage) then I should probably close this conversation for now. I wasn't trying to be critical before, just helpful. I hope that what I wrote was not perceived in that way. I am actually quite appreciative of your help and the other devs help on this project. Thanks for the explanation/your patience.
