### ISSUE TITLE
use cloudflare pages/workers for manifest

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#152]
At the moment there is no good way to deliver `intro-skipper` for different versions of Jellyfin.
But Lucky Jellyfin sets the version in the useragent header, e.g. `Jellyfin-Server/10.8.13`.

Depending on which version we get, we can serve the correct manifest.

**Comment by jumoog** [comment]
quick [prototype](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbMutvvsDMAjJ3wOwA2ACwBWTvwCcADhGjBkngCYpABgX9p-AFwc9+tjz4S5EmXIXK1GrQFgAUAGF0VCAFNX2ACJQAzjHRfKGgXbRIMLDwCYhIqOGA3BgAiKBo3AA8AOgArXyTSVCgwD3jElLSs3KSHZ1cPCGwAFToYNzC4GBgwKABjAigXZGy4ADc4Xx6EWAgAamB0XHA3BwcMgKQSXDdUOHAIEgBvewBIZAAqM5OSM5IAAXgEeMOAJTcARxA3XwgAXxIEd6fb5XG63AEQEAIKi+Q4ABQQ6GAfjcAB5Xv4XL43AA+H4g5D2EgkcZ0Kg9cJuCA9AAWAAoAR8vhAAJSHQlEkg9TH7EBYhAAQQA5vUSAx-oCmZlqW44FsEL5MsKILSAOQAVT52CF9RVzPZRKgqBItN5bgFwtcmW+iAgvgA6sE6SqAFJuMBgOiFKjYADKZpGZuQ3FUmWkmV1rKOHI54MhVBI6IC0LcOV8LlpAG19dG2Tmc0lBSAoLgkmEkj1pJxcLIyGRsHBuG5VNhhD1OKJ69xeNg3Epg9weqhhG43IIyEkADTZvNJOIJUskJIASVcCJIPoA1rBWghJ9P8+gAwgRlA3AB3BdJfkgCCI-p9d10TaUtw9fZwGgkXxbmAkVIQBEYVSEh3GKE8ghcEg3BgPwFi+Pc82jJItgmKYYBCKhL35OIPQALy+EDpWJEBcAGEh0CNUC3HAgZ42g2CUOJT8tncN8gNXBYQDfWivwlMkvkyBDEKJJJ0DPKgzUvbIQHmdBBQnEh+TID9cBcNxcEcG1jQiDd1PCBFgBIWpUFNXBYXQMBEAAIRlBBmSE4TywINxBUwOhLwAcQ8M04DABzEJSYA4GFNUED8stqQgCAYF8bRkGQR4z0VR0QDIU0EC5OpLS5YAhhk9A5OQf8EWwb9t0DILvkDKAguFXxkDAOT0EyGAqEFfyZyPCDoQXLNhOjKN+qQrraMvENuEybgw1UDr+vLakP2FRr2rLbB1xHQi3HCcAwE5Ba2rdOTiX2DMPOCAAJVKAF1aUi6LYviwUUrITIcry2TBSKjjSp-HdkDIRqyGQSr3AQZBHHO-kADkPIAUQAGQAeQ8zJgFwZkAB1MKnIakMIBAlSUqBL2DUNMmETIZpx3GRLTSEejcULwsXO6Yri5AnogalUtexF3oKz7ivQH7yrBgFinGL5kFU8TGtlIMQ2kZARnGybpq+gDhbKzozWwFXJrVynMlw2BZscmlXw3XwZMvVAZDgHZVHkVBBEEHpVGkLsu1UJRcFwX3e0kfhVFQfgzYC6AEmtYAYEvJQfeEbAnaTyRGj7bRhB0dsAC0kn3PMfmpobBpppIRpcMaDe4fhKfDmcaUWw6VsXNa-S2rmtpM909sb5bjpIU6Luu26orZx7nt53LpI+jWSu1v6AfQIGQcDCHobhpGUbRzHsfziPEEJshibLUmwwpqm95nOmMsZsLL1Zh6OYnt7p4F2etd+wNxZlLF6plqg5a4AVqGZWqtq6U3fiLHWCA9ZgJriGE2sci643mpba2wBLycDcBIf2ZBvaiG4LgbgohVA9GENIUQZACG4EELgRQ4gyA9DrvmSOTJ4ixzLPHJQidVCJ2DI0Ls2gCHaCmrnS+HJC7iKJCXFB5dMJljAYIWuyChrzV7nJS8rcNod22t3BuB0+4EAHmdCAl0yA3QfuzTm3MXov3yoVIWUCF6A2BuMUG4NIYwwRsjVG6MsbMLxgfSkRMSaK3JsoqRHIkjXwZkze+o9H7WJ5nYmejj55fzdD-KW-9AGgKroISB6SYH6wmtwJRiCAlRItj0K2NsyzSBkJIHoZA3BNOEJwaQuBRANmEDsMgnBVA+17AOJQY44CVJEqw6OHDFxcJ4ZwJOwgBGqBESsnOecaZ4iGldPeWycxXT1NGP4bosR-iNCaPk2pLTWiQPaR0qpXSPi9L6f0gZSaSHDMySM+5YxQgTF8JMWJUzpj6ohGRM5CzFkvBWKsNY6wNibC2NsHYGzdmGaoAcQ4RxjmYbOUol4Vya3XJ-XcKiDxHhPOeLCN47zQAfB6Z8rF3yfm1n+Di7EQKZJopBeiaYUK4pQpMaYo0yzYV8nQfCMIdG7FIugcilEuV+B4ryuCMIVKMtfLaNlmtFjcUgliRk-EFS4rEhJXcZZX5yQUkpFSakNJaVpDpPSqADJGRcCZLEZkLLWVsvZMlSE+juFcvQTy3lHh+X9VEmqwVb7MySJY+KiVkpc1SulTK7hsp80tYLb6RTXFVTBtGuqDUmotTariuReQwiguLpEkScjK5KCNhfGmIl9FLQ0atda7ciJd12u2pu-dB6mOHgmp+KbbFZvsTmzWTjAyL2Xm41eniN4+O3v4yNM58aH2Poud5zaJmLhibG+J90rHPynak3NJKEqZMln-U1uT3kAFIlAADEQxNpDKoQpJLsBjn4LgBmohjam03fmaptSMFljgAoMgvsqG8EkKQgZuBOCoFEKIVA8dhBuzIFoYcYdwN4xqmwmOccE6LOwPw1QkhtADJEfwMRmzxE7OEns6MBzszHLAKc8F4oIR-Ikmef5GJky0iSFDOVjyPReiSIciR7JJE-CIPYNTDgDCab0EYAQpgpCyDEJYbgKhkM2H4DUFwGaGg+AxEEDCYQIg4HwIQUgc4ygJEIM58ZBQiglASMkBd1QnCWfqE0FobRiSdG6IG2iQw0xUBWPYA4SQgqpAAPrzEWMUUs5QtiVDyD8DTWnissB0yYMQZgDPyEUMZ6wQctDMAcEAA)

**Comment by AbandonedCart** [comment]
Does it support reading from a file? The only issue I foresee with that is the precession to update it.

**Comment by jumoog** [comment]
- We can redirect
- Update the Worker

**Comment by jumoog** [comment]
Other plugins put everything in a manifest as well, so that seems to be fine for the time being.
