### ISSUE TITLE
[Bug]: Memory leak

### ISSUE THREAD

**Issue by phyzical** [jumoog/intro-skipper#172]
### Describe the bug

I'm pretty sure there is a massive memory leak occurring.

![image](https://github.com/jumoog/intro-skipper/assets/5182053/9e20d286-2520-4054-b50a-bffa05a97456)

i only have 1 job that ran at exactly midnight and it looks to be this plugin's 
![image](https://github.com/jumoog/intro-skipper/assets/5182053/7c4db374-5f5b-4b95-bd92-52e454d55104)

it is 1pm at time of this screen shot, so 13 hours past the memory leak
![image](https://github.com/jumoog/intro-skipper/assets/5182053/ed115b2b-eda7-4e26-bdd0-e4f7d8ae630e)
![image](https://github.com/jumoog/intro-skipper/assets/5182053/354fcb86-f624-4fb6-8002-9385d439d22c)

The amount of ram is crazy, but whatever. it should atleast be releasing things so i think theres a memory allocation/caching mechanism bug somewhere

maybe loading in the cache xml o.0

### Jellyfin installation method

docker

### Container image and tag

jellyfin 10.9.1,  intro skipper 0.2.0.4

### Operating System

unraid

### Support Bundle

```shell
* Jellyfin version: 10.9.1
* Plugin version: 0.2.0+f1d34991162a
* Queue contents: 94589 episodes, 5669 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment]
https://github.com/jellyfin/jellyfin/issues/11551

**Comment by phyzical** [comment]
@jumoog 

Im pretty sure its not playback related. (unless the way that intro skipper works hits a similar path in jellyfin)

just to be clear in my screen shot, that initial memory usage is with playback.

as soon as intro skipper runs i see a spike that never goes away

in the linked thread i see there is another user with the issue that has intro skipper installed ill try to see if they also had it running when the spike occurred 

![image](https://github.com/jumoog/intro-skipper/assets/5182053/2c73d08b-63a3-4e72-bf14-1f92986517a2)

**Comment by phyzical** [comment]
ah yeah looking at that threead, it could be a side effect as some notice ffmpeg process zombieing. which is what this uses

**Comment by AbandonedCart** [comment]
If that is the case, then it would be a flaw in the specialty ffmpeg provided alongside jellyfin.

**Comment by phyzical** [comment]
Yeah i agree, but that's assuming that's the problem. will report back when the linked issue gets some sort of resultion
