### ISSUE TITLE
[Bug]: Status shows 'NotSupported" after update .8 version

### ISSUE THREAD

**Issue by SkyDiver7199** [jumoog/intro-skipper#184]
### Describe the bug

The plugin just auto updated from .7 to .8 as i launch my Jellyfin server. 
Old version was superseded and did the restart, the plugin status shows "NotSupported: right after. 
Nothing works, can't even bring up the plugin setting. 
![image](https://github.com/jumoog/intro-skipper/assets/125536789/974057db-84fd-4fac-8ef9-d788a7f06327)

### Jellyfin installation method

Windows

### Operating System

Windows 10

### Support Bundle

```shell
Can't even access the plugin settings now
```

### Jellyfin logs

```shell
[2024-05-27 19:13:00.174 +08:00] [ERR] [8] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "C:\ProgramData\Jellyfin\Server\plugins\Intro Skipper_0.2.0.8\ConfusedPolarBear.Plugin.IntroSkipper.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
```

**Comment by jumoog** [comment]
Please upgrade to Jeyllfin `10.9.3`

**Comment by theS1LV3R** [comment]
Can this be reflected in the README.md too? Currently it says at least `10.9.2`

**Comment by jumoog** [comment]
> Can this be reflected in the README.md too? Currently it says at least `10.9.2`

It helped?

**Comment by theS1LV3R** [comment]
Yep, updating to `10.9.3` fixed the issue

**Comment by SkyDiver7199** [comment]
it works after update to 10.9.3. 
But the skip intro button is still not visible on my web browser. 

The automatic skip intro works tho

**Comment by sukritpant** [comment]
I am facing the same issue, I was on Jellyfin 10.9.6 and upgraded it to the latest build of Jellyfin 10.9.8 but it still does not work. It says the same not supported message.

**Comment by rlauuzo** [comment]
Make sure your plugin repository URL is set to: `https://raw.githubusercontent.com/jumoog/intro-skipper/master/manifest.json`
