### ISSUE TITLE
[Bug]: Jellyfin after update to 0.2.0.8 is not supported

### ISSUE THREAD

**Issue by JaneQ14** [jumoog/intro-skipper#188]
### Describe the bug
Jellyfin Version 10.9.2
![obraz](https://github.com/jumoog/intro-skipper/assets/63305812/462e33ec-1c89-490e-b229-07651abfe4bd)

### Jellyfin installation method

Windows Installer

### Operating System

Windows 10

### Support Bundle

```shell
I can't check it because the plugin is broken
```

**Comment by jumoog** [comment]
Please upgrade Jellyfin

**Comment by JaneQ14** [comment]
I have Jellyfin Version 10.9.2

**Comment by JaneQ14** [comment]
Ok, sorry. My server does not show that there is an update. Sorry, close the topic. is version 10.9.3

**Comment by JaneQ14** [comment]
![obraz](https://github.com/jumoog/intro-skipper/assets/63305812/f396ea48-490a-4a4e-8564-9358199997b5)
![obraz](https://github.com/jumoog/intro-skipper/assets/63305812/08fa0eb6-99b5-4949-899b-a7a3b6838a82)

**Comment by Stooovie** [comment]
Where do you get a plugin version 0.2.0.8? The repo is set correctly but JF 10.9.4 only shows Skipper v0.1.18.0. 

![IMG_9514](https://github.com/jumoog/intro-skipper/assets/10572373/47862a4b-28be-4764-9ab3-ed223cb0c021)
![IMG_9513](https://github.com/jumoog/intro-skipper/assets/10572373/60c76bff-e1a7-4644-8d76-a92110ae2ca0)

**Comment by jumoog** [comment]
the correct url for 10.9 is `https://raw.githubusercontent.com/jumoog/intro-skipper/master/manifest.json`. The URL you use is for 10.8.

**Comment by Stooovie** [comment]
You're right. Thanks!

**Comment by MajorSquaLL** [comment]
i have version 
10.10.5, the application does not work on my end.

**Comment by AbandonedCart** [comment]
> i have version 10.10.5, the application does not work on my end.

Which application? This is only a plugin to provide the times for the client.

**Comment by isntfunny** [comment]
For me it also seems like it doesn't work anymore. At least for the latest show I am watching.

Version 10.10.5, Plugin latest version.

**Comment by AbandonedCart** [comment]
> For me it also seems like it doesn't work anymore. At least for the latest show I am watching.
> 
> Version 10.10.5, Plugin latest version.

Sounds like your issue is that the show didn’t have chapters and the chromaprint couldn’t find matching audio that met the requirements in your settings.

This issue here was missing a Jellyfin update.

**Comment by starrbuck68** [comment]
> the correct url for 10.9 is `https://raw.githubusercontent.com/jumoog/intro-skipper/master/manifest.json`. The URL you use is for 10.8.

Getting a 404 for this URL.

**Comment by jumoog** [comment]
https://intro-skipper.org/manifest.json
