### ISSUE TITLE
[Bug]: Intro-Skipper Not Queueing Entire Library

### ISSUE THREAD

**Issue by FlawedSyntx** [jumoog/intro-skipper#212]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

The plugin seems to install correctly, and I have restarted Jellyfin both within the UI and/or from the CLI. However, the scheduled tasks run nearly instantly and are only scanning 2 episodes of a single show. For reference, my entire Show library is 1770. I read through issue 174 but my issue seems different because that issue's queue appeared to match the expectation, and then fail to reach it. While my queue is only 2 episodes and does not match the expectation.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

linuxserver/jellyfin:latest

### Operating System

Ubuntu 24.04 LTS

### Support Bundle

```shell
* Jellyfin version: 10.9.7
* Plugin version: 0.2.0+6f127ca7bf58
* Queue contents: 2 episodes, 1 seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

```shell
[2024-07-13 18:33:43.388 -04:00] [INF] [51] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean Intro Skipper Cache" Completed after 0 minute(s) and 0 seconds
[2024-07-13 18:33:45.073 -04:00] [INF] [41] ConfusedPolarBear.Plugin.IntroSkipper.DetectIntrosCreditsTask: Scheduled Task is starting
[2024-07-13 18:33:45.116 -04:00] [INF] [41] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Movies"
[2024-07-13 18:33:45.117 -04:00] [INF] [41] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library "Shows"
[2024-07-13 18:33:45.122 -04:00] [INF] [41] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Intros and Credits" Completed after 0 minute(s) and 0 seconds
```

**Comment by FlawedSyntx** [comment]
Unfortunately, that still resulted in the same, only 2 episodes in the queue.

**Comment by jumoog** [comment]
Is it possible to play back the files in Jellyfin?

**Comment by FlawedSyntx** [comment]
Yes. The files work fine otherwise in Jellyfin. But the skipping function is not working of course. None are stored locally though. They are mounted from a lan file server. Perhaps that impacts it somehow? Not sure how it found the 2 episodes it did though because they are also on the fileserver.

**Comment by jumoog** [comment]
> Yes. The files work fine otherwise in Jellyfin. But the skipping function is not working of course. None are stored locally though. They are mounted from a lan file server. Perhaps that impacts it somehow? Not sure how it found the 2 episodes it did though because they are also on the fileserver.

My entire library is on a NAS and everything is mounted with Samba. So thats not a problem.

**Comment by AbandonedCart** [comment]
Random thoughts:

Try adding something in the option for scanning specific libraries, saving, clearing it, and saving.

Try disabling chromaprint for detection and running a scan.

Try enabling the option not to use cache.

That ensures it’s not an issue with some rogue filter, not ffmpeg, and not that automatic detection or something else just saved a bunch of garbage cache files.

**Comment by FlawedSyntx** [comment]
> Random thoughts:
> 
> Try adding something in the option for scanning specific libraries, saving, clearing it, and saving.
> 
> Try disabling chromaprint for detection and running a scan.
> 
> Try enabling the option not to use cache and running a scan.
> 
> That ensures it’s not an issue with some rogue filter, not ffmpeg, and not that automatic detection or something else just saved a bunch of garbage cache files.

I tried the first step with a cache clear before and after using the scheduled task. Still ran instantly and found only the two episodes.

Tried the second step, again with a cache clear before and after using the scheduled task. Still ran instantly and found only the two episodes.

Tried the third step first with a cache clear before and after using the scheduled task and then again after erasing all introduction timestamps globally using the button at the bottom of the manage Fingerprints tab. I checked the box for cached fingerprints to be deleted as well. This time it took about 30 seconds but still only found the two episodes.

I then tried the first two steps with the erase step this time instead of just the scheduled task. They each ran instantly and only retrieved the same two episodes. 

I tried to only make one adjustment at a time to make sure I could track what made a difference specifically.

**Comment by AbandonedCart** [comment]
Is there anything special about the two it detects or anything about them that they have in common with each but not the other 1768 items?

**Comment by FlawedSyntx** [comment]
Not anything that I can figure out honestly. They are just in the same directory alongside all the others. They play normally and don't seem to be any different.

**Comment by AbandonedCart** [comment]
That is a strange one.

**Comment by rlauuzo** [comment]
There was/is an issue where creating a new library may cause some shows or episodes to be incorrectly passed to the plugin or not passed at all. This typically resolves itself after performing a manual full library rescan or refresh. I assume that's also what happened in [issue #174](https://github.com/jumoog/intro-skipper/issues/174).
