### ISSUE TITLE
[Feature Request] Bring improvements to desktop client

### ISSUE THREAD

**Issue by Bretterteig** [jumoog/intro-skipper#222]
Currently the desktop client plugin still has the old design of the skip button and also does not support the new keyboard controls. 
As the JMP is also a web version I thought it might be possible to port the enhancements to this version as well

**Comment by jumoog** [comment]
We can't change the desktop client because the code is built into the client. Please post your request to the desktop client [repo](https://github.com/jellyfin/jellyfin-media-player).
