### ISSUE TITLE
Choose another location for edl files

### ISSUE THREAD

**Issue by parasiteoflife** [jumoog/intro-skipper#229]
I'm using Jellyfin with Docker, my media is mounted as read-only for security this means Intro Skipper can't write edl files next to the video files, could you please add an option to write edl files to another location (would be great if it stored all those files in the data directory instead of the library).

**Comment by AbandonedCart** [comment]
It was always my understanding that the EDL files had to be written alongside the video because that is how they are detected.

**Comment by jumoog** [comment]
This could be implemented, but then you have e.g. 2k edl files in one folder.

**Comment by rlauuzo** [comment]
EDL files are only for Kodi and must be in the same folder as the video file. For more information, see [Kodi's EDL documentation](https://kodi.wiki/view/Edit_decision_list#Supported_File_Formats).

**Comment by jumoog** [comment]
> EDL files are only for Kodi and must be in the same folder as the video file. For more information, see [Kodi's EDL documentation](https://kodi.wiki/view/Edit_decision_list#Supported_File_Formats).

ok thanks you for clarifying

**Comment by AbandonedCart** [comment]
> EDL files are only for Kodi and must be in the same folder as the video file. For more information, see [Kodi's EDL documentation](https://kodi.wiki/view/Edit_decision_list#Supported_File_Formats).

Don't forget MPlayer
