### ISSUE TITLE
[Bug]: Skip Button Not Apearing and Auto Skip Not Working

### ISSUE THREAD

**Issue by JH1089** [jumoog/intro-skipper#230]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

Im sorry if this is a dupe, i have recently updated to Jellyfin 10.9 and the intro skipper seems to have stopped working. It used to work when i was on 10.8. It seems to be scanning correctly (at least the same as when it was working) but when i play anything regardless of settings i cant get the skip button to appear nor auto skip to work. Any help would be much appreciated :)
Also im pretty new at all this so please talk to me like a child lol

### Jellyfin install method

Windows Installer

### Container image/tag or Jellyfin version

Jellyfin:10.9.8 Intro Skipper:0.2.0.14

### Operating System

Windows 11

### Support Bundle

```shell
* Jellyfin version: 10.9.8
* Plugin version: 0.2.0+c0708528f0d2
* Queue contents: 6934 episodes, 493 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13-win32 (GCC)
configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Follow the instructions provided [here](https://github.com/jumoog/intro-skipper?tab=readme-ov-file#skip-button-is-not-visible) to get the skip button working.

There was also an issue when updating from 10.8 that made timestamps invalid. To fix this, go to the plugin settings and use the "Erase all introduction timestamps (globally)" option (do not check "Erase cached fingerprint files").

**Comment by JH1089** [comment]
> There was also an issue when updating from 10.8 that made timestamps invalid. To fix this, go to the plugin settings and use the "Erase all introduction timestamps (globally)" option (do not check "Erase cached fingerprint files").

This fixed it, thank you :)

**Comment by JH1089** [comment]
One last question, is it possible to get it working on app versions of jellyfin, like the desktop app or the firestick app? Or is it exclusive to the web version? Because i think i recall it working on the app versions with jellyfin 10.8

**Comment by rlauuzo** [comment]
On the desktop app, you can enable it in the client settings under Plugins. Currently, it does not work on Android TV or Fire TV.

**Comment by JH1089** [comment]
perfect thank you :)

**Comment by jumoog** [comment]
You can enable "Automatically skip intros" in the options.

**Comment by AbandonedCart** [comment]
Well, that checkbox turned out to be about as effective as I expected.
