### ISSUE TITLE
[Bug]: Manage Fingerprints only shows 1 season (Season -1)

### ISSUE THREAD

**Issue by accountForIssues** [jumoog/intro-skipper#233]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

I use Kodi (latest on Google Play) along with Jellyfin. JF is installed on my NAS and Kodi on my Android 12 box.

In Manage Fingerprint and Logs, I can only seem to select `Season -1`. There are no other options. This doesn't affect the skipping as all episodes have been scanned/cached. The seasons show up fine on JF/Kodi. It's only in this section.

I previosly assumed `Season -1` would be the last but it is usually a random season from the show.

![image](https://github.com/user-attachments/assets/a2eb5839-4667-44a0-b66e-c3d9fefb95f0)

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

jellyfin/jellyfin:latest

### Operating System

QNAP NAS Linux 5.10.60-qnap

### Support Bundle

```shell
* Jellyfin version: 10.9.8
* Plugin version: 0.2.0+c0708528f0d2
* Queue contents: 3419 episodes, 266 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment]
`-1` is stored in the metadata 

you can set Season number to -1
![screenshot](https://github.com/user-attachments/assets/fb220b7a-584e-48d6-8317-87ec30340083)

**Comment by jumoog** [comment]
I changed that for testing and now i also have -1
![test](https://github.com/user-attachments/assets/498b8ded-998d-4c86-8696-1d9cbfa0c1f4)

**Comment by jumoog** [comment]
Its not a Plugin Bug

**Comment by accountForIssues** [comment]
I don't understand. It's all fine everywhere else as I mentioned. Where can I see where this -1 is coming from ?

![image](https://github.com/user-attachments/assets/ecfcfa13-d0f8-432b-8ee2-a9fc6c9199fb)

**Comment by rlauuzo** [comment]
Try doing a full library rescan in the Jellyfin dashboard. 
![Screenshot_20240731_223631_Jellyfin](https://github.com/user-attachments/assets/bd6caa73-769a-4f5b-94c7-26de69b0997c)

**Comment by jumoog** [comment]
and restart jellyfin

**Comment by AbandonedCart** [comment]
> replacing all metadata within a season folder

The plugin itself doesn't interact with nfo files. The information is passed from Jellyfin. It's possible that that nfo files weren't allowing Jellyfin to pass that information to the plugin, even if it could be displayed to you.

**Comment by accountForIssues** [comment]
@VampiricAlien Pretty sure it's in the Jellyfin DB. I dunno much about the code base or the DB so could be wrong, but I believe the plugin requests/gets the `AiredSeasonNumber` from Jellyfin and if it isn't available, a default of -1 is returned.

Now, depending on your metadata provider, that may or may not be filled. I don't use Jellyfin for managing metadata (I use tinymediamanager) so recreating nfo's doesn't help.

I dunno what Jellyfin itself uses to display the Season number as that info is correct even if the -1 still shows up in the plugin.

**Comment by AbandonedCart** [comment]
You’ll need enough metadata in jellyfin to identify the show, season, and series. As to whether you need to delete the files, the plugin doesn’t read them.

**Comment by Hello-World-Traveler** [comment]
> You’ll need enough metadata in jellyfin to identify the show, season, and series. As to whether you need to delete the files, the plugin doesn’t read them.

@AbandonedCart I've notice if you delete the nfo files then refresh metadata, the plugin will work with that show. Refreshing metadata without deleting the files doesn't do anything. If the libraries have 100's of nfo files, what is the best way to go about this? the nfos are there as a backup for JF.

**Comment by AbandonedCart** [comment]
> I've notice if you delete the nfo files then refresh metadata, the plugin will work with that show. Refreshing metadata without deleting the files doesn't do anything. If the libraries have 100's of nfo files, what is the best way to go about this? the nfos are there as a backup for JF.

You already quoted how you should handle it. Unfortunately, keeping the files means you either need to manually enter the metadata into jellyfin or find a way to automate copying it. 

The reason what you are doing _appears_ to work is that by deleting the files, jellyfin fills the data in locally. This is why you still have to refresh after deleting the files. From the sound of it, jellyfin will use an NFO file, but not import the data. That seems like something that should be discussed with jellyfin, since it has adverse side effects.

**Comment by Hello-World-Traveler** [comment]
This command `find . -type f -name "*.nfo" -delete` removed all nfo files.

Is it possible for the plugin to read and write to nfo or would their not be much point with Jellyfin 10.10?

**Comment by AbandonedCart** [comment]
Again, the plugin does **not** interact with nfo files.
