### ISSUE TITLE
[Bug]: Plugin not showing in catalog

### ISSUE THREAD

**Issue by pousoupou** [jumoog/intro-skipper#239]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

After I added your repo, the plugin was not showing up in the catalog. Restart of the server did not fix it. Nothing about that in the log file.

### Jellyfin install method

Windows Installer

### Container image/tag or Jellyfin version

jellyfin 10.9.6

### Operating System

Windows 10

### Support Bundle

```shell
well....
```

**Comment by jumoog** [comment]
Upgrade to `10.9.8`

**Comment by pousoupou** [comment]
Oh my god. Sorry. I just now saw that I am running an old version. Notification to new one never came. I feel stupid

**Comment by jumoog** [comment]
It's okay. There are no Notification.
