### ISSUE TITLE
[Bug]: auto skip intro not working with the android app

### ISSUE THREAD

**Issue by jaum20** [jumoog/intro-skipper#247]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

1. Activate auto skip intro
2. Scan lib to identify intros
3. Play some episodes on android jellyfin
4. Intros no skipped
5. Play same episode on the web player
6. It works (intro skipped)

### Jellyfin install method

Linux swizzin

### Container image/tag or Jellyfin version

Jellyfin 10.9.9, intro-skipper 0.2.0.15

### Operating System

Debian 12

### Support Bundle

```shell
* Jellyfin version: 10.9.9
* Plugin version: 0.2.0+92aa5fef8806
* Queue contents: 621 episodes, 38 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12 (Debian 12.2.0-14)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by rlauuzo** [comment]
Try removing your Android device from the device list in the Jellyfin dashboard. After that, you'll need to log in again on your Android device.

**Comment by jaum20** [comment]
Didn’t worked

**Comment by AbandonedCart** [comment]
Does it work when you access your server through a browser?

**Comment by AbandonedCart** [comment]
The Android app is allegedly just a wrapper around the web player. When you tested it on the web, do you use the browser on your phone?

**Comment by jaum20** [comment]
> The Android app is allegedly just a wrapper around the web player. 

I am using the integrated player on the Android app. Can this be the problem? 

>When you tested it on the web, do you use the browser on your phone?

Yes

**Comment by rlauuzo** [comment]
If you start playing something on the Android app, can you control the playback (e.g., play, pause) from the dashboard on the web client?

**Comment by jaum20** [comment]
> If you start playing something on the Android app, can you control the playback (e.g., play, pause) from the dashboard on the web client?

Nope. It just shows the info and message buttons. Also, I tried do change to the default player and the auto skip worked

**Comment by jumoog** [comment]
If you can't control the device (play/pause) from the server dashboard, there's not much we can do.
See also #168

**Comment by CasuallyFilthy** [comment]
I had this issue and the fix was installing the latest android tv client. I had an old version due to playback issues in 0.17.x, but being on 16.11 preventing me from using auto skip. Upgrading to 0.17.4 fixed the issues with intro skipper
