### ISSUE TITLE
Androidtv app not working with this plugin

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#25]
So, for the androidtv jellyfin app (0.16.2) found here: https://github.com/jellyfin/jellyfin-androidtv, this plugin does not work. The popup appears, but the media is not skipped. If I post an issue on the jelyfin androidtv app github the response I get is: "We do not support third party plugins. Please open an issue with the author." So, not sure what to do. I tested the webapp and the jellyfin media player desktop app and this plugin works great for both of those, just not the androidtv app. Is there something different about the way the tv app works? Any way to recompile it to get this plugin to work? Okay, thanks.

Edit: Spelling typo.

**Comment by jumoog** [comment]
it worked on the older version of the androidtv app?

**Comment by d8f6** [comment]
It did. It stopped working after version 0.16.0. So, the change was recent whatever it was. I would just downgrade the app, but the current version fixes some crashes I was having. I still get the on screen notification of intro being skipped, but aside from the notification nothing happens.

**Comment by jumoog** [comment]
OK, I'm going to see if I can reproduce it.

**Comment by jumoog** [comment]
Okay, I can reproduce it. But it seems to be a problem with the Android TV app. Because even with the official Android app, I can't control the TV app.

**Comment by jumoog** [comment]
https://github.com/jellyfin/jellyfin-androidtv/issues/3263

**Comment by d8f6** [comment]
Thanks for checking/filing an issue. I guess for now downgrading to the last beta release may work. Should I close this issue now since it cannot be fixed on this end? Also, when you say that you cannot control the app does that mean playback also cannot be stopped from the app/server? I suppose that is an issue that may get fixed. Thanks for your help with this.

**Comment by jumoog** [comment]
> Thanks for checking/filing an issue. I guess for now downgrading to the last beta release may work. Should I close this issue now since it cannot be fixed on this end? Also, when you say that you cannot control the app does that mean playback also cannot be stopped from the app/server? I suppose that is an issue that may get fixed. Thanks for your help with this.

Yes the playback cannot be stopped from the app/server.

**Comment by jumoog** [comment]
This problem will be fixed in the next version of the app (v0.16.3). In the meantime, you can build your own app and use this PR: https://github.com/jellyfin/jellyfin-androidtv/pull/3253

**Comment by jumoog** [comment]
0.16.3 is out and intro skipping works again

**Comment by jumoog** [comment]
> > 0.16.3 is out and intro skipping works again
> 
> I find this to be working on Android app and web but not ATV, is it just me?
> 
> Updated to 0.16.3

ATV?

**Comment by jumoog** [comment]
How do you update? The latest version is 0.16.4. Both 0.16.3 and 0.16.4 work fine in my tests.

**Comment by jumoog** [comment]
Maybe I don't use tunneling
