### ISSUE TITLE
Question: Does introskipper detect chapters?

### ISSUE THREAD

**Issue by DexLuther** [jumoog/intro-skipper#265]
The question is  sort of in the title, but I've been wondering if the introskipper detects chapters and then simply skipping chapters labeled with some of the most common terms (OP, opening, Intro, etc)? 

I believe Plex handles it this way (I only had Plex Pass for about a month ages ago), and then maybe cromaprints everything else.

**Comment by AbandonedCart** [comment]
Yes. The phrases detected can be configured in the plugin settings and it’s prioritized before lengthier scans to help optimize speed.
