### ISSUE TITLE
[Feature request] Ability to blacklist a show/season

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#28]
So, some shows have repeating audio and/or chapter segments that are introductory in terms of audio fingerprinting, but are also critical and/or part of the story. It is rare that this is the case, but I have seen it in two shows. What I would like is the ability to blacklist a show/and or season (season would probably be preferrable) so that it is ignored/not scanned by intro-skipper.

Edit: I did not see a template, so I hope that I am placing this request in the right section. It is not a bug/issue.

**Comment by jumoog** [comment]
I don't plan to add any new features at the moment, just fix bugs. But if you want, you can do a PR.

**Comment by d8f6** [comment]
Okay, thanks got getting back.
