### ISSUE TITLE
[Bug]: Not showing up in Plugin Catalog

### ISSUE THREAD

**Issue by miasinterestinglife** [jumoog/intro-skipper#284]
### Self service debugging

- [X] Jellyfin is updated (10.9.9) and my permissions are correct (or I did not use Docker)

### Describe the bug

I am unable to install this Plugin as it doesn't appear in the Plugin Catalog after adding the repo - not even in the other sections - and even restarting multiple times. My current version (10.9.3) is the newest I can install, there is no update being shown available.

### Jellyfin install method

TrueCharts

### Container image/tag or Jellyfin version

10.9.3

### Operating System

TrueNAS-SCALE-23.10.2

### Support Bundle

```shell
can't check since I'm unable to install
```

**Comment by miasinterestinglife** [comment]
This was an issue with the Truecharts plugin since it didn't get updated anymore. Fixed by switching to a native app install.

**Comment by xHaruke** [comment]
i am also having the same issue on jellyfin v10.9.9.. how do i fix it?

**Comment by jumoog** [comment]
install 10.9.11
