### ISSUE TITLE
[Bug]: Bundle in tizen client

### ISSUE THREAD

**Issue by Ulrar** [jumoog/intro-skipper#285]
### Self service debugging

- [X] Jellyfin is updated (10.9.9) and my permissions are correct (or I did not use Docker)

### Describe the bug

Hi,

Probably shouldn't really be reported as a bug, but discussions don't seem to be enabled on the repo. Sorry if there was a better way to engage that I missed.

The [tizen Jellyfin client](https://github.com/jellyfin/jellyfin-tizen) isn't published to the official app store, you're expected to build it yourself. It uses jellyfin-web and packages it as an app, so I thought intro-skipper may work with it. Instead of downloading an compiling the jellyfin-web sources from git, and packaging the dist folder, I instead grabbed the 'web' folder from my jellyfin server and packaged that.

I thought these would contain all the intro-skipper files, since it works on my jellyfin web, but the resulting app does not show the buttons.

Wanted to ask for any tips, hints or recommendations on how to make this work and/or debug it. Is there for example a way for me to add the intro-skipper frontend bits to the jellyfin-web sources myself, instead of grabbing my container's web folder ?
Is there a way to know if a given client has the UI elements, short of launching an episode and waiting for the button to pop ?

Thanks !

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

linuxserver/jellyfin:latest

### Operating System

Unraid, but trying to get this working on jellyfin-tizen

### Support Bundle

```shell
N/A
```

**Comment by jumoog** [comment]
use this [patch](https://github.com/jumoog/intro-skipper/blob/master/webui.patch) to integrate the button into `jellyfin-web`

**Comment by jumoog** [comment]
And I enabled discussions in that repo.

**Comment by Ulrar** [comment]
Awesome, that worked, the intro skip button shows up on my TV now. Appreciate the help !
