### ISSUE TITLE
Add skip button when casting

### ISSUE THREAD

**Issue by dredstone1** [jumoog/intro-skipper#290]
When casting an episode there is a remote controller, add skip button to this remote controller.

![IMG_20240916_114951.jpg](https://github.com/user-attachments/assets/9ab20511-8ca9-4bf8-8753-b31ff54b6e14)

**Comment by AbandonedCart** [comment]
Doesn't casting depend on the capabilities of the app receiving the request?

**Comment by dredstone1** [comment]
Yes.
But we can still add buttons to the remote controller using js

**Comment by dredstone1** [comment]
> Will you be able to test against Chromecast, Web TV, Roku, etc?

it doesn't matter, because it will all happen inside the remote controller interface(the same as the player)

**Comment by AbandonedCart** [comment]
So you'll be able to test a casting feature without casting? Think about that for a minute.

**Comment by dredstone1** [comment]
No, I will be able to test that using chromecast and it should work with any other device, and I still can test that in any other device.
I think that your question is not a good question, and this is just an idea that can be implemented.

**Comment by AbandonedCart** [comment]
I think you're missing the point here. You're suggesting a feature and then arguing it doesn't require testing based on the good faith that because it works for you, it will work for any variation of the same concept.

**Comment by dredstone1** [comment]
I said that:
> and I still can test that in any other device.

I don't understand where is the problem?
I said that your question is irrelevant because it doesn't have nothing to do with the app who receives the casting, it's like asking me if I can test the pause button on the remote controller interface when casting to different devices(it something that needs to be tested like every other edge case). 
It didn't work for me because Its just an idea that can be implemented in the future.
This is a feature request.

**Comment by AbandonedCart** [comment]
This isn’t really within the scope of servers or clients and if you are casting enough to need a skip button, there is likely a client made for the device.

**Comment by AbandonedCart** [comment]
https://github.com/jellyfin/jellyfin-chromecast
https://www.amazon.com/Jellyfin-for-Fire-TV/dp/B07TX7Z725
https://github.com/jellyfin/jellyfin-webos
https://github.com/jellyfin/jellyfin-roku

**Comment by dredstone1** [comment]
“That’s where the confusion starts. I don’t really care about it because when the button is clicked,
 it will move to the specified time via the remote control. This has nothing to do with the app receiving the casting.
The ‘problem’ you’re talking about doesn’t actually exist.
There isn’t any compatibility issue because it will all be handled by JavaScript in the remote control interface.”
But if you haven’t understood that by now, you probably won’t get it now either.

**Comment by AbandonedCart** [comment]
You can drop the attitude. I'm well aware of what point you think you're making and you're wrong.

The problem is that you're relying on the receiver to execute the button press that is sent back to the casting device. You're also relying on it to display a custom control UI that is not part of the standard controls.

**Comment by dredstone1** [comment]
When you say "relying on the receiver to execute the button press that is sent back to the casting device" it's misleading because it's the same as I rely on it to execute the move 10s forward button. Auto skip also "relies on the client" to execute the skip. This feature exists on Netflix and there is no reason it will not exist here. Like I said this is just a feature request like others (intro skipping for movies, Setting don't Skip last Episode)...

**Comment by AbandonedCart** [comment]
I offered you a compromise. Come back to it after you take a moment to cool off.

**Comment by dredstone1** [comment]
what is the compromise?

**Comment by AbandonedCart** [comment]
Treat it like PiP

**Comment by dredstone1** [comment]
so it will always auto skip?

**Comment by AbandonedCart** [comment]
If you never toggle the setting off, it would seem that way. 

The concern is the UI. The skip code runs on the casting device. The UI isn’t just displaying a button. It’s also size, shape, color, placement, etc etc. Eliminate the need to manage the button and you remove the risk.

That’s not to say as it’s **confirmed** to display and function on devices, they can’t transition to a button. The issue is throwing it out there untested and assuming it will work.

**Comment by dredstone1** [comment]
i really confused right now because you are describing my idea with all of the appropriate concerns.

**Comment by AbandonedCart** [comment]
> When casting an episode there is a remote controller, add skip button to this remote controller.

I’m actually saying **not** to attempt providing a button and instead allow setting a skip on cast option and then revisit the button idea with actual testing.

**Comment by dredstone1** [comment]
OK that sounds great, its not what i said because i never said how the proceed will be, this is why i put it as a feature request, i don't want to do that, for now.

**Comment by AbandonedCart** [comment]
Sure. Then I’ll go ahead and remove that discussion.
