### ISSUE TITLE
[Feature Request] Skip Intro/Credits via crowdsourced timestamps (like sponsorblock)

### ISSUE THREAD

**Issue by tundrablasen** [jumoog/intro-skipper#291]
I searched the issues but didn’t found anything and just wanted to put an idea out there. 

Wouldn’t it make sense to add the possibility to report timestamps where intros/credits starts and end?

Similar what [Sponsorblock](https://github.com/ajayyy/SponsorBlock) does for YouTube videos.

**Comment by AbandonedCart** [comment]
As much as I love Aniskip, there are a lot of moving parts. A server to host the database, verification, the million and two variations of a single episode. It’s a good idea that would take a lot of time and planning to execute.

**Comment by tundrablasen** [comment]
That’s true,. How is sponsorblock is doing it? Anybody has insides?

You probably would need a md5 hash of a file + time stamps

**Comment by AbandonedCart** [comment]
The video hash maybe? YouTube video instances are unique, so that is a slight advantage.

**Comment by jumoog** [comment]
I already had this idea in mind, but I don't want to host this database.

**Comment by jumoog** [comment]
> The video hash maybe? YouTube video instances are unique, so that is a slight advantage.

fingerprinting like VLC does

**Comment by jumoog** [comment]
Maybe we can do something like export/import as a JSON file and people can share those files. But I guess the timing is different between languages and specials, so it doesn't make much sense.

**Comment by jumoog** [comment]
The last time I searched, people weren't even sharing their Kodi EDL files.
