### ISSUE TITLE
Re-scanning same show of different length reuses old intro timing 

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#40]
So, I have noticed that if I replace an episode with the same episode of a different length, delete the timestamps for that season, and rescan then the same timestamps are generated that were used from the original scan. I am wondering if there is also a cache somewhere that I should be deleting/or the program should delete but isn't (should I restart the server after doing this?). Hopefully what I am saying makes sense. If someone else can confirm/test this I would appreciate it. I have reproduced this issue on more than one show. 

Edit: 
Server - Ubuntu 20.04
Jellyfin.Server 10.8.13.0
Intro Skipper 0.1.8.0
jellyfin-ffmpeg 4.4.1-4

**Comment by jumoog** [comment]
OK, I will look into it.

**Comment by AbandonedCart** [comment]
There is a cache in the folder created to store the intro details. It's possible when the values are removed that it isn't being deleted.

**Comment by AbandonedCart** [comment]
There is an option now to disable using the cache. If you are familiar with the plugin folder for Jellyfin, you can also delete the cache folder in the configurations/intro folder there. If you want to use it and just start over, deleting the folder is all you need.

**Comment by d8f6** [comment]
Okay, so I see the new option after updating. So, after unchecking I need to rescan my entire library for intros/credits and then it will work like it used to, but without the cache? I will not need to rescan the entire library ever time I delete timestamps for a season or add new shows after this? I just want to make sure I understand as my library is sort of big/server is not super fast so this process will probably take a while.

**Comment by AbandonedCart** [comment]
If you specified the libraries to scan in the plugin, this will only apply to those. If not, this will apply to all of them.

Disabling cache will run a full scan on everything that the plugin scans. It will not skip anything. It will do this every single time. Disabling cache is really only meant for smaller servers that have constantly changing, but similar media.

Deleting the folder will run a full scan the next time, but will cache that scan for following scans.

If you can get the episode ID of a specific episode with issues, you can also delete the individual cache file to scan just that episode.

**Comment by d8f6** [comment]
Yes, you are right. That is the feature I need. It would be better to be able to delete a cache for individual seasons though in my opinion as this is already sort of the way it works (or so I thought initially). The UI is designed in this way/for this function already seemingly. I will keep this issue open for now. Thank you for your help.

**Comment by AbandonedCart** [comment]
Looks like there was an option to clear a single season buried in the fingerprint editor. I'm working on making it more accessible and reliable. It's not a single show, but at least it's only a single season.

**Comment by AbandonedCart** [comment]
I added the necessary code to delete the cache for a single episode. Now it's just a matter of figuring out how to go about making it accessible from the configuration.

**Comment by d8f6** [comment]
Apparently deleting cache for a season now works. I was unaware that this got fixed. I have not tested this yet personally, but going to close this issue now.
