### ISSUE TITLE
[Clarity/Feature request?] Automatically skip credits

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#41]
I am unsure of how skipping credits works. I turned the automatic skip intros feature on, and it works great, but is skipping credits automatically not a thing? Or is there an option that is not in the gui that I need to turn on or a config file to edit somewhere to achieve this? Okay, thanks in advance for any additional information.

**Comment by jumoog** [comment]
The automatic skipping of credits is not implemented.

**Comment by d8f6** [comment]
I see. Okay, thank you for clarification.
