### ISSUE TITLE
inject javascript button 

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#48]
try to inject like https://github.com/nicknsy/jellyscrub does

**Comment by jumoog** [comment]
https://github.com/nicknsy/jellyscrub/blob/main/Nick.Plugin.Jellyscrub/JellyscrubPlugin.cs#L38

**Comment by AbandonedCart** [comment]
Are there clients out there that use their own local copy of the web player?

**Comment by jumoog** [comment]
yeah injecting the pluging javascript in the existing index.html

**Comment by AbandonedCart** [comment]
https://github.com/jumoog/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/Plugin.cs#L332

I mistook the backup page as what was being used. Isn't this already the same injection?

**Comment by jumoog** [comment]
omg i never had the button. After cleaning browser cache its there

**Comment by AbandonedCart** [comment]
This feature also resolved a whole mess of upstream issues

https://github.com/ConfusedPolarBear/intro-skipper/issues/201
https://github.com/ConfusedPolarBear/intro-skipper/issues/194
https://github.com/ConfusedPolarBear/intro-skipper/issues/190

**Comment by AbandonedCart** [comment]
This feature also resolved a whole mess of upstream issues and integration requests

https://github.com/ConfusedPolarBear/intro-skipper/issues/18
https://github.com/ConfusedPolarBear/intro-skipper/issues/106
https://github.com/ConfusedPolarBear/intro-skipper/issues/153
https://github.com/ConfusedPolarBear/intro-skipper/issues/159
https://github.com/ConfusedPolarBear/intro-skipper/issues/189
https://github.com/ConfusedPolarBear/intro-skipper/issues/190
https://github.com/ConfusedPolarBear/intro-skipper/issues/193
https://github.com/ConfusedPolarBear/intro-skipper/issues/194
https://github.com/ConfusedPolarBear/intro-skipper/issues/201
