### ISSUE TITLE
Intro uses 100% ram

### ISSUE THREAD

**Issue by ShakeSp33r** [jumoog/intro-skipper#50]
Intro skipper while scanning media eventually eats up all 16GB of ram and then crashes Jellyfin server.
This happens every time I run a scan, intro skipper scan gets to about 80% and then hits 100% ram usage.
For the last couple of months, I disabled the scan and the ram usage is 3GB, but as soon as I start the scan the memory usage starts climbing and don't get released.

Jellyfin : 10.8.13
Intro Skipper : 0.1.8.0

**Comment by jumoog** [comment]
Docker?

**Comment by ShakeSp33r** [comment]
Yes,

linuxserver/jellyfin

**Comment by jumoog** [comment]
Okay where do you see the 100% ram usage?

**Comment by ShakeSp33r** [comment]
When running docker stats, under normal use (before intro scan) the memory usage is 3.338GiB, after running the intro scan, it jumps up to 10Gib, and don't release it again.

I also used BpyTOP and before the scan MemB is showing 2G, but after a scan it shows 9G, and the only why to get it back down is to restart the container.

**Comment by jumoog** [comment]
Please try 
```shell
sync; echo 1 > /proc/sys/vm/drop_caches
```
in your host system to write the kernel cache to disk. If the Docker statistics are still the same, let me know.

**Comment by ShakeSp33r** [comment]
I've started the scan and let it run through the entire library, left Jellyfin for about 4 hours even though the scan only took 57min. Run the above code on the host and it did not help. It reduced by small amount, but after running the above this is the result:
`CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
d88386b79996   jellyfin        1.63%     8.422GiB / 15.55GiB   54.17%    251MB / 19GB      18.4GB / 144GB    43`

I restarted the Jellyfin container, used Jellyfin for about 30min and this is the result (Jellyfin always hovering around these figures if the Intro scan is not enabled - even after a week of use)
`CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
d88386b79996   jellyfin        0.22%     2.64GiB / 15.55GiB    16.98%    874kB / 466kB     2.01GB / 1.66GB   42`

**Comment by AbandonedCart** [comment]
This was also being seen in the upstream.
https://github.com/ConfusedPolarBear/intro-skipper/issues/199

I think lowering the priority of the ffmpeg process will reduce how much RAM it eats up because Jellyfin sets it to unlimited by default.

**Comment by jumoog** [comment]
I cannot experience this myself and therefore cannot recreate it. What kind of movies do you have? mkv files? does the ffmpeg process hang up?

**Comment by ShakeSp33r** [comment]
Yes, all files are MKV, x265.
I have not noticed that the ffmpeg process hang up

I've checked the log and the only "errors" found was a couple Chromaprint returned 0 points for,  but nothing else

**Comment by AbandonedCart** [comment]
What do you have set as your "degree of parallelism"?

**Comment by ShakeSp33r** [comment]
Analyze show extras : **OFF**
Max degree of parallelism :  **2**
Cache episode fingerprints : **ON**

**Comment by AbandonedCart** [comment]
What happens  when you set that to 1?

**Comment by ShakeSp33r** [comment]
Have not tried that yet, will do and report back

**Comment by AbandonedCart** [comment]
By setting (or leaving) the priority of ffmpeg at below normal, setting 1 thread, and setting parallelism to 1, you should be able to run the app on a machine with a single core processor. That isn't a direct impact to RAM, but only dealing with one scan or one video at a time will reduce the amount of RAM in turn.

**Comment by ShakeSp33r** [comment]
So I removed Intro completely, including cache and any config/trace to it.

Install v 0.1.16.1, made sure the config was parallelism=1 and ffmpeg priority=below normal, as for the rest I left it as default and rescan the entire library (hoping that it was some file being corrupt or something). Things looked optimistic as the RAM usage grew to 5Gig and then drop down to 2/3Gig, After the full scan the RAM usage was back at 9/10Gig, so I restarted Jellyfin and scheduled a Intro scan at 01h00, thinking that no new files were added, it should not do much and RAM usage should be minimum. 
Checking this morning after the scan, it was back at 10.91Gig.
Tried drop_cache andRAM usage reduced to 10.10Gig.

Not sure what to try next.

**Comment by AbandonedCart** [comment]
It sounds like the issue is happening after the plugin is finished running. Do you have other plugins installed?

**Comment by ShakeSp33r** [comment]
aniDB, AudioDB, Fanart, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Session Cleaner, SkinManage, Studio Images, TMDb, TheTVDB

**Comment by jumoog** [comment]
can't reproduce
