### ISSUE TITLE
disable cache trigger full scan

### ISSUE THREAD

**Issue by jumoog** [jumoog/intro-skipper#51]
When I disable the cache. Intro Skipper performs a full scan each time

**Comment by AbandonedCart** [comment]
I probably should have added a note about that. That's how it should work. The whole cache system needs an update to make sure it's always the same file being scanned. As far as I can tell, it only verifies names and not video length or anything like that. Not using cache at all is a bit of a workaround for that.

**Comment by jumoog** [comment]
Good thing I didn't delete the folder. Scanning 10TB takes some time 😂
