### ISSUE TITLE
After clicking on skip intro, button still appears 

### ISSUE THREAD

**Issue by UriSheinman** [jumoog/intro-skipper#52]
So the "show skip button for intro duration" is amazing, but an issue I've been having is that it skips the intro but still shows the button after it's being pressed. Video example below

https://github.com/jumoog/intro-skipper/assets/132785427/a3608469-c540-4eae-bace-16eaaa5a65d1

**Comment by AbandonedCart** [comment]
Does holding down shift and reloading the page help? I haven't seen this personally, so I'm wondering if it is a stale browser cache

**Comment by UriSheinman** [comment]
> Does holding down shift and reloading the page help? I haven't seen this personally, so I'm wondering if it is a stale browser cache

This is in findroid so not really an option

**Comment by AbandonedCart** [comment]
I'll install it and see what's up

**Comment by AbandonedCart** [comment]
What are your settings for the plugin skip prompt? (times for how early to display it, how long, and how much intro to play)

**Comment by UriSheinman** [comment]
![Screenshot_20240302-205052](https://github.com/jumoog/intro-skipper/assets/132785427/d0a7719a-2eff-4b47-91d2-f8977a4fa15e)

**Comment by AbandonedCart** [comment]
In the video, it looks like every time you click it, it goes back to the end of the intro. If you let it go for 7 seconds, does it disappear?

**Comment by UriSheinman** [comment]
> In the video, it looks like every time you click it, it goes back to the end of the intro. If you let it go for 7 seconds, does it disappear?

No cause the "show for duration of intro" is checked. It does go away eventually it just takes a few secs after the intro is skipped.

**Comment by AbandonedCart** [comment]
That's what I thought. It's keeping the button up because "technically" it is still playing the intro for a few seconds.

**Comment by UriSheinman** [comment]
Is there a way to change that? So after the button is pressed it stops showing?

**Comment by AbandonedCart** [comment]
I'm pushing it now

**Comment by UriSheinman** [comment]
Wdym?

**Comment by AbandonedCart** [comment]
The plugin will be updated as soon as confirm the fix works.

**Comment by AbandonedCart** [comment]
https://github.com/jumoog/intro-skipper/pull/53 fixes this. It is v0.1.13

**Comment by UriSheinman** [comment]
I don't know if it's a plugin side error but I have been trying to update the plugin for the past hour, but it still reports as ver 0.1.10.0 even tho the version in the plugin folder is 0.1.13.0.
![1709411266501942002444866652552](https://github.com/jumoog/intro-skipper/assets/132785427/6830b89b-1732-4c95-97d5-8e6dae6ebe1e)
![17094112852662021561905733221677](https://github.com/jumoog/intro-skipper/assets/132785427/510af2e4-74cb-489b-914e-2dae4a930e40)
And if it is the latest version it still doesn't work:

https://github.com/jumoog/intro-skipper/assets/132785427/ac907252-4d83-4c4d-b675-2bccc8008fd3

**Comment by AbandonedCart** [comment]
That is unusual. It appears to be working now on my end, but I think the .10 you are seeing is the binary version. I didn't update that, so it's still showing the old one.

**Comment by UriSheinman** [comment]
Anyway the issue still persists so no luck with the fix...

**Comment by AbandonedCart** [comment]
Did you restart the server and reload the app?

**Comment by UriSheinman** [comment]
Yes, multiple times.

**Comment by AbandonedCart** [comment]
https://github.com/jumoog/intro-skipper/assets/1173913/56461355-83d3-4d25-854c-c8a2bec8faf5

Seems like the issue may be in the app because it works in the browser version after the update, but the app still has a delay before the button disappears.

**Comment by UriSheinman** [comment]
> Untitled.video.-.Made.with.Clipchamp.mp4 
> Seems like the issue may be in the app because it works in the browser version after the update, but the app still has a delay before the button disappears.

I think this was always the problem... As I said I don't use the desktop app when I do the skip button is fine... Is there a way to fix this from here or should I post it on findroid github?

**Comment by AbandonedCart** [comment]
I think you're waiting on https://github.com/jarnedemeulemeester/findroid/pull/633

**Comment by jumoog** [comment]
> > Untitled.video.-.Made.with.Clipchamp.mp4
> > Seems like the issue may be in the app because it works in the browser version after the update, but the app still has a delay before the button disappears.
> 
> I think this was always the problem... As I said I don't use the desktop app when I do the skip button is fine... Is there a way to fix this from here or should I post it on findroid github?

yes there is a delay in findroid but only 1 second

**Comment by AbandonedCart** [comment]
A temporary fix would be to set the amount of intro to play as 0

**Comment by UriSheinman** [comment]
> A temporary fix would be to set the amount of intro to play as 0

Ill try

**Comment by UriSheinman** [comment]
> A temporary fix would be to set the amount of intro to play as 0

Doesn't work but I guess it's the best that can be done...

**Comment by AbandonedCart** [comment]
https://github.com/jarnedemeulemeester/findroid/blob/main/player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt#L247-L262

They are determining when the button is displayed on their end. I don't know if there is a check somewhere else, but it's essentially keeping the button visible the entire time the intro is playing. That means if you play 3 seconds of intro after the button is pressed, it will still be visible for that 3 seconds. That's the issue I fixed on our end. They would need to fix it on theirs.

**Comment by AbandonedCart** [comment]
The PR for skipping credits should improve that overhang a bit. @cd16b was nice enough to include shaving a second off the end to offset the check delay.
