### ISSUE TITLE
Updating this plugin

### ISSUE THREAD

**Issue by VampiricAlien** [jumoog/intro-skipper#55]
You currently have version 0.1.10.0 installed.

I upgraded from 0.1.8.0 to 0.1.10.0 the other day however no matter how I install 0.1.10.0, 0.1.11.0, 0.1.12.0 or 0.1.13.0 I end up with 0.1.10.0. Deleting the plugin and manually installing doesn't fix it, removing the plugin and restarting to install it again doesn't change anything as I always end up with 0.1.10.0 installed.

Is this an error with the plugin or my sever?

I also notice on https://github.com/jumoog/intro-skipper/blob/v0.1.13/manifest.json  0.1.13 is not listed?

**Comment by AbandonedCart** [comment]
The binary details weren't being updated for the releases. A lot of stuff was done locally by the legacy (ConfusedPB) plugin author off site and has to be recreated now that the plugin is being updated again.

**Comment by AbandonedCart** [comment]
Got everything lined up so the version number will match the update
