### ISSUE TITLE
Skip to preview instead of next video

### ISSUE THREAD

**Issue by AbandonedCart** [jumoog/intro-skipper#66]
In Anime, there is typically a preview after the credits. Should we be skipping to that, instead of moving to they next video? This could also be an optional behavior.

Although it may only be possible to identify the preview in files with chapters, since the current methods only find the start of the credits and can't determine the end.

**Comment by Eeeeelias** [comment]
I think, if at all, it should be optional behaviour. I personally don't want to see the preview (especially when the next episode is coming up either way) so keeping it an option would be great.

**Comment by AbandonedCart** [comment]
I used to skip them until a few shows did other stuff with the segment.

**Comment by rlauu** [comment]
> In Anime, there is typically a preview after the credits. Should we be skipping to that, instead of moving to they next video? This could also be an optional behavior.
> 
> Although it may only be possible to identify the preview in files with chapters, since the current methods only find the start of the credits and can't determine the end.

That's exactly how the modified web interface handles skipping with the on screen skip button. It jumps straight into the preview content, if available.
