### ISSUE TITLE
New update breaks "Support Bundle Info" output

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#67]
When clicking the "Support Bundle Info" dropdown arrow the output is: "Error processing request.". Unsure if whether any other functionality is affected, but wanted to point out the issue. All other option dropdown arrows seem to be working properly.

Installed version: 0.1.16.1

**Comment by AbandonedCart** [comment]
Apparently this was originally being populated during a scan and now that the requirements are optional, it isn't populated. Easy enough to fix.
