### ISSUE TITLE
[Bug]: season 0 episodes that are automatically placed within seasons are scanned regardless of analyze season 0 setting and breaks manual fingerprint editor 

### ISSUE THREAD

**Issue by quixotic120** [jumoog/intro-skipper#82]
### Describe the bug

if an episode from season 0 is included within a season due to tvdb metadata it is automatically scanned, ignoring "analyze season 0" being unchecked despite absence of extras folder.

further, when going to change erroneous fingerprints within a season where this occurs it is not possible, the only episode that appears in the dropdown for the season is the one pulled from specials.

<details><summary>screenshot</summary>
<img width="1182" alt="Screenshot 2024-03-17 at 5 09 15 PM" src="https://github.com/jumoog/intro-skipper/assets/16725261/d90ebfd5-d6c9-4956-a473-44c3c832e536">
</details>

screenshot of library showing what I mean - season 4 of family guy with the last 4 episodes replaced with the movie of the same episodes from specials

<details><summary>screenshot</summary>
<img width="493" alt="Screenshot 2024-03-17 at 5 10 18 PM" src="https://github.com/jumoog/intro-skipper/assets/16725261/0608d006-1663-4eed-835a-51b768514a3d">
</details

managing fingerprints showing the season is listed out of order

<details><summary>screenshot</summary>
<img width="498" alt="Screenshot 2024-03-17 at 5 10 29 PM" src="https://github.com/jumoog/intro-skipper/assets/16725261/3de32638-076b-4e9a-b7a2-1811a8591c7c">
</details

showing that is the only selectable episode within the season

<details><summary>screenshot</summary>
<img width="522" alt="Screenshot 2024-03-17 at 5 10 39 PM" src="https://github.com/jumoog/intro-skipper/assets/16725261/94e317de-7f62-45c4-a354-831b078ac226">
</details>

once selected fingerprints for said episode do not load. this is inconsistent; I have gotten fingerprints for said episode to load.

also comes up for anime with OVAs released in-between seasons and that's where fingerprinting tends to be more problematic for me. I can autoskip what is believed to be the intro or get the skip intro button from patched webui to appear so everything is getting fingerprinted, just cannot access the fingerprints for episodes once they are fingerprinted

also thanks for maintaining this project!

### Jellyfin installation method

docker

### Container image and tag

jellyfin 10.8.13 bbergle image, introskipper 0.1.16+7032816cbeb6

### Operating System

docker is debian base, running on unraid

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+7032816cbeb6
* Queue contents: 8040 episodes, 606 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by AbandonedCart** [comment]
> despite absence of extras folder

I have a feeling that may be part of what is causing the issue. If Jellyfin is showing the specials as part of season 4, the plugin doesn't know they aren't.

**Comment by AbandonedCart** [comment]
You also don't need the old custom web-ui. This one injects it into the stock build.

**Comment by quixotic120** [comment]
My specials are in a folder called "Specials", sorry if that was unclear. 

for family guy the directory structure is as follows:
Specials/S00E01 - Stewie Griffin The Untold Story.mkv
...
Season 4/Episode1.mkv, etc.

They are pulled into the season because thetvdb has a tag for "special position" to indicate where to place it in the library. See https://thetvdb.com/series/family-guy/episodes/181165 - special position places it "before season 4, episode 28" 

so in the Jellyfin library it is pulled from the specials index and placed in the season 4 index despite the fact that it is placed in a separate folder. 

I typically ignore scanning specials but these are getting scanned because of this. The only issue really I am having here is the fingerprint editor being broken as a result; a different show has this issue but the fingerprinting is off and I can't adjust the timings because only the special is selectable in the editor. 

will look into getting rid of the custom webui, thanks for the heads up! and either way thanks for your time!!

**Comment by AbandonedCart** [comment]
Is this still an issue after all the recent changes?

**Comment by quixotic120** [comment]
Same behavior with 0.1.17.0

**Comment by AbandonedCart** [comment]
Thanks. Ill take a fresh look

**Comment by jumoog** [comment]
can't reproduce
