### ISSUE TITLE
Add support for SyncPlay

### ISSUE THREAD

**Issue by PeachesMLG** [jumoog/intro-skipper#87]
### Describe the bug

Skipping intro when using sync play doesnt work correctly.

If I click the skip intro button, it will skip ahead, and then skip backwards to where I was before

### Jellyfin installation method

Docker

### Container image and tag

jellyfin/jellyfin:latest

### Operating System

Ubuntu

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+7032816cbeb6
* Queue contents: 8658 episodes, 503 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by jumoog** [comment]
already know https://github.com/ConfusedPolarBear/intro-skipper/issues/151

**Comment by jumoog** [comment]
The problem is that no one owns the SyncPlay group sessions. Everyone is allowed to seek. And as a plugin I have to select a member or the group to send a seek command on its behalf.

**Comment by jumoog** [comment]
With the current state of SyncPlay, this is not easy. I've played with SyncPlay a bit and when I refresh the browser tab, I'm no longer in a SyncPlay group. It would probably be necessary to create a user that automatically joins all SyncPlay groups.
