### ISSUE TITLE
Missing "Automatically skip Credits"

### ISSUE THREAD

**Issue by mrld341** [jumoog/intro-skipper#88]
I see "Automatically skip Intro" checkbox in plugin settings but don't see "Automatically skip Credits" or "Automatically press Next"
So I assumed that this checkbox would apply to both (Into and Credits), but it doesn't seems to be the case.

Intro is getting skipped automatically, however end credits still require you to press or hover your mouse on to "Next" button.

_Why have "Credit Detection" in scheduling tasks if there is no way to automatically skip it after it was detected?_

Can somebody please advise how to make it work? I just need button "Next" to be clicked automatically when it pops out during credits. 
 
I saw similar request in other places. But not for this plugin.  Is there another plugin that needs to be added to make this work, or could current [intro-skipper] include that?

**Comment by AbandonedCart** [comment]
It should probably be a separate option.

**Comment by mrld341** [comment]
@jumoog I see you mentioned this is another thread.
What do you think, is adding "Automatically skip Credits" or "Automatically press Next" button is something you could possible do? Or that's is not something you looking to add to [intro-skipper] ?

**Comment by phyzical** [comment]
having a quick look at the code https://github.com/jumoog/intro-skipper/blob/10.9/preview/ConfusedPolarBear.Plugin.IntroSkipper/AutoSkip.cs

its not a simple "just add support for also credits" as it also makes a bunch of assumptions around being called at the start of the episodes.

Im  not 100% sure how it knows to "start checking for a skip" do these just keep polling and the early exits avoid anything happening after the the skip/ when no intro to be skipped is detected?

i can probably have a crack at this though if @AbandonedCart or @jumoog know the answer to the above?

**Comment by mrld341** [comment]
@phyzical Did somebody figure it out or decided not to do this feature?
I see you linked requested, but it says "Closed".

**Comment by AbandonedCart** [comment]
https://github.com/jumoog/intro-skipper/pull/103

**Comment by mrld341** [comment]
@phyzical  @AbandonedCart 
I tried to check #103  but it says that something is broken in new Jelly Fin version and now no work can be done on this?  
Or is there another thread?
Sorry I don't really understand how Github works with linking these random threads to each other.

Is there some rough version that just skips end credits without UI checkbox? I would test it if you advise on how to install such...

**Comment by AbandonedCart** [comment]
I thought that link was the work in progress.

**Comment by phyzical** [comment]
@mrld341 its forked off of the 10.9 source atm i think. but i have not been able to get the credits scan to work so i cant actually progress it atm.

**Comment by mrld341** [comment]
Tested it, seems to work most of the times.
There is a bug, when you go through "recently viewed" episode, sometimes instead of going to the next episode on the list, it would go back to the menu.
However, when played trough "Shows" - "Name of specific show" - "Season" - "episode X" . Always works and goes to next episode automatically 100% of the time. 
Thank you!

**Comment by AbandonedCart** [comment]
You can change the message in the plugin settings. I believe I forgot to change the default from intro to credit. At least the copy paste mistake was something you can change, I guess.

**Comment by mrld341** [comment]
> You can change the message in the plugin settings. I believe I forgot to change the default from intro to credit. At least the copy paste mistake was something you can change, I guess.

Oh, you right, I didn't even realize you can expend "User Interface Customization" and there are things inside.  That solves notification issue.

**Comment by AbandonedCart** [comment]
Glad to hear it. I also fixed the default. It never got changed. The cost of trying to save 30 seconds.

**Comment by d8f6** [comment]
Feature is working great, thanks for this. I have a question and did not want to start a new issue: For the scheduled tasks do I need to do this order?: 

1. Detect\ Intros
2. Detect\ Credits
3. Detect\ Intros\ and\ Credits

Or is everything handled in the "Detect Intros and Credits" scheduled task now? I use jellyroller to automate all this from a script, just want to make sure I am doing it correctly/not wasting time with steps 1 and 2.

**Comment by AbandonedCart** [comment]
Last one covers everything and is the only one set to run (at midnight). The other two are there for special circumstances (you want intros now and you'll let the rest get handled overnight). That also pre-dated the automatic tasks getting cleaned up. Sadly, they don't provide a clear way to order them or the combined one would be first.

**Comment by d8f6** [comment]
Understood. Thank you for the quick reply.

**Comment by AbandonedCart** [comment]
I imagine something like a debug setting on the configuration page to launch them from that would be ideal or at least I can add a note that it's optional extras.
