### ISSUE TITLE
[Bug]: "Ignore intro in the first episode of a season" functionality inverted?

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#89]
### Describe the bug

In the settings there is an option (checkbox) entitled: 
Ignore intro in the first episode of a season
The description is written as:
If checked, auto skip will ignore introduction in the first episode of a season.

I assumed that this meant if this box was unchecked, then first episode would also have introduction skipped automatically. It seems that the opposite is true though (when checked, episode skips). Based on the description it seems that ignoring auto skip would mean that the first episode introduction is not skipped, but the opposite is true in my case. Re-writing the description would probably be the fastest way to remedy this issue. If someone else could confirm this behavior that would be great. Okay, thanks in advance.

### Jellyfin installation method

apt

### Operating System

Ubuntu 20.04

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+7032816cbeb6
* Queue contents: [Redacted] episodes, [Redacted] seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by AbandonedCart** [comment]
Functionality isn't inverted. It's just confusing. It ignores the first episode in the analysis.

**Comment by d8f6** [comment]
Well, I am unsure about analysis (I would have to add new media to test this and get back to you). But, when the box is checked, it skips the intro in the first episode of a season and when it is not, it doesn't. It still works, but I do find the description confusing/misleading. Not really a big deal since I can set the option and forget it forever, just wanted to point out my observation.

**Comment by AbandonedCart** [comment]
Alright. Thanks for the report.

**Comment by AbandonedCart** [comment]
It was a lot of double negatives, so now the checkbox will play the intro in the first episode of a season and it's enabled by default. Hopefully that solves it.

**Comment by d8f6** [comment]
Testing and working as it should now. Thank you for the quick fix. Going to close this bug now.

**Comment by AbandonedCart** [comment]
Thanks for reporting it. I apologize for assuming it was confusion. I thought I had made changes I hadn't.

**Comment by d8f6** [comment]
@AbandonedCart 
No need to be apologetic as I took no offense whatsoever. I am genuinely appreciative for your help with this plugin and look forward to any continued development.
