### ISSUE TITLE
[Bug]: After updating to v0.1.16.4 running "Detect Introductions" scans whole library

### ISSUE THREAD

**Issue by d8f6** [jumoog/intro-skipper#93]
### Describe the bug

So, after updating and running the "Detect Introductions" scheduled task it seems to be rescanning my whole library. Initially I thought it was just stuck, but looking at the jellyfin log it shows that the plugin is scanning, just scanning everything. I am just going to let it run to completion I suppose, but if someone else can verify this behavior I would appreciate it. If it is necessary I understand, but should probably be documented in the release notes assuming that this is not a bug. I'm wondering if maybe this has to do with the "Testing the new release actions" commit from yesterday? Any clarity and/or verification would be appreciated. 

### Jellyfin installation method

apt

### Operating System

Ubuntu 20.04

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+ccb3bbc6835f
* Queue contents: [Redacted] episodes, [Redacted] seasons
* Warnings: `UnableToAddSkipButton`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by AbandonedCart** [comment]
The analysis always scans your entire library and uses the cache to speed it up. If your cache was cleared for whatever reason, then those items are not there to speed it along. The commit you mentioned was to change what is printed to the console when a zip file is made. That will have absolutely no impact at all on the plugin inside it.

**Comment by d8f6** [comment]
I see. Well, the "Cache episode fingerprints" box is still checked (I did not make any changes there). Aside from unchecking the box "Play intro for first episode of a season" I did not make any changes on my end at all. If you manually run the "Detect Introductions" scheduled task is it still working as intended on your end? Usually it finishes on my end after about 3-5 minutes after adding one season, right now I am at 2% after approximately 50 minutes. I tried restarting the jellyfin service to make sure that wasn't a culprit, but that had no impact.

**Comment by AbandonedCart** [comment]
I don't think my system will be an accurate representation of how long it should take. My entire scan is 5 minutes when it's having a rough time.

**Comment by d8f6** [comment]
Ah, gotcha. Hopefully someone with a relatively large library can weigh in. It could be related to the issue you mentioned, although I think this issue started for me after the most recent update (as far as I know). If you run a scan does the jellyfin log show that the task is analyzing every show in your library? I can see what is happening in the logs eg: 

ConfusedPolarBear.Plugin.IntroSkipper.DetectIntroductionsTask: Analyzing 11 files from "ShowName" season 1
ConfusedPolarBear.Plugin.IntroSkipper.DetectIntroductionsTask: Analyzing 11 files from "ShowName2" season 1
etc..etc...

I'll stop the scan, downgrade and then try again and see if I get different results.

**Comment by d8f6** [comment]
Tested after downgrade, but wound up with same result. I'm at a loss. The cache does seem to be working properly though as stopping and restarting scan resumes where it left off according to the log file.

**Comment by AbandonedCart** [comment]
Somehow, somewhere, your cache got cleared.

**Comment by d8f6** [comment]
That seems like the most logical explanation. Unsure how though as I did not do the clearing. Well, if no one else is experiencing this issue and you cannot reproduce it on your end, then it is not a bug. Going to close now. Will reopen/post again if issue arises again.

**Comment by d8f6** [comment]
Cannot reproduce. Typing this as I forgot to click the close button, and do not know how to do it without a comment here.

**Comment by AbandonedCart** [comment]
It's the Jellyfin cache, so it's hard to say if that randomly cleared it. That may be one of the reasons it was previously kept out of there, but I guess that can be determined if this starts becoming a recurring problem.

**Comment by d8f6** [comment]
Difficult to say. If it is the scheduled cache clear task, then soon there should be more reports here by other people withing the next few days. After poking around my filesystem it seems like skip times cache is stored in /var/cache/jellyfin/introskipper/chromaprints ? I suppose I could just make all the created files there immutable after creation. I'm going to backup that folder after this run just in case so I can restore them and report back tomorrow or the day after if this issue pops up again (going to take ~20 more hours to complete scan).

**Comment by d8f6** [comment]
After running all tasks everthing seems to be working normally now. Unsure of what happened. Must've been some type of fluke. chromaprints folder has been backed up, but the directory of files is larger than the system can handle to backup normally (unsure if this is related, still looking into it). Seems to have been a problem on my end though as far as I can tell.

**Comment by ArdianaLeek** [comment]
Same thing happened to me after the Clean Cache Directory task ran.
 I had it set to run every 24 hours but this is the first time when it seems to have cleared the chroma prints too

**Comment by AbandonedCart** [comment]
They were moved to the cache directory. ☠️

**Comment by d8f6** [comment]
As part of my normal scanning script I run the "Clean Cache Directory", so this could definitely be the issue. I guess I should not run this except for a scheduled task instead of right after scanning? Or should this scheduled task be turned off completely because it interferes with this plugin?
