### ISSUE TITLE
[Bug]: Skip button broken in v0.1.16.4 on Webos in certain situations

### ISSUE THREAD

**Issue by rlauuzo** [jumoog/intro-skipper#94]
### Describe the bug

The Intro Skipper plugin's skip button extends to an excessive length in specific scenarios on WebOS. This occurs when the Jellyfin "play next episode" dialog has been displayed at the conclusion of the previous episode. The issue appears to be isolated to WebOS and v0.1.16.4 and has not been replicated on Firefox or with plugin version v0.1.16.3.

![20240328_114431](https://github.com/jumoog/intro-skipper/assets/46294892/198911a7-b976-4b14-b506-b1cec555711a)

### Jellyfin installation method

Docker

### Operating System

Webos

### Support Bundle

* Jellyfin version: 10.8.13
* Plugin version: 0.1.16+ccb3bbc6835f
* Queue contents: 3481 episodes, 250 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by AbandonedCart** [comment]
Nothing in the parameters has changed since https://github.com/jumoog/intro-skipper/pull/78, so is that causing the issue?

**Comment by rlauu** [comment]
Its a possibility that the nested CSS selectors are contributing to this.  It seems the upNextContainer width isn't being reset as intended, causing the skip button to inherit an exaggerated width from its parent element.

**Comment by rlauu** [comment]
This is what copilot says:

> The CSS you provided has a syntax issue. You're attempting to nest media queries and pseudo-class rules directly within the #skipIntro selector, which isn't valid CSS syntax. Instead, you should define media queries and pseudo-class rules outside of the main selector.
> 
> Here's the corrected version:
> 
```
> css
> 
> #skipIntro {
>   padding: 0 1px;
>   position: absolute;
>   right: 10em;
>   bottom: 9em;
>   background-color: rgba(25, 25, 25, 0.66);
>   border: 1px solid;
>   border-radius: 0;
>   display: inline-block;
>   cursor: pointer;
>   box-shadow: inset 0 0 0 0 #f9f9f9;
>   transition: ease-out 0.4s;
> }
> 
> #skipIntro.upNextContainer {
>   width: unset;
> }
> 
> #skipIntro:hover {
>   box-shadow: inset 400px 0 0 0 #f9f9f9;
>   transition: ease-in 1s;
> }
> 
> @media (max-width: 1080px) {
>   #skipIntro {
>     right: 10%;
>   }
> }
> 
> @media (hover:hover) and (pointer:fine) {
>   #skipIntro .paper-icon-button-light:hover:not(:disabled) {
>     color: black !important;
>     background-color: rgba(47, 93, 98, 0) !important;
>   }
> }
> 
> #skipIntro .paper-icon-button-light.show-focus:focus {
>   transform: scale(1.04) !important;
> }
> 
> #skipIntro #btnSkipSegmentText {
>   padding-right: 3px;
>   padding-bottom: 2px;
> }
```

**Comment by AbandonedCart** [comment]
I'm looking into ways to make it more compatible with old browsers, since I vaguely remember that being the issue before.

**Comment by rlauu** [comment]
Thanks! The new preview release fixed the issue.

**Comment by rlauuzo** [comment]
The issue has resurfaced on 10.9.

**Comment by AbandonedCart** [comment]
The only change box time recently was the animation and that was verified. Does webos have a console that would log error messages? I'm wondering if the issue is somewhere else this time.

**Comment by rlauuzo** [comment]
I believe 10.9 is lacking this commit https://github.com/jumoog/intro-skipper/commit/9e7d0a74f0cc11d996703d16d5352b89f9be5ae6

**Comment by AbandonedCart** [comment]
That would explain it. That undid the incompatible nesting.

**Comment by jumoog** [comment]
thanks i added the changes.. new release tomorrow

**Comment by AbandonedCart** [comment]
Thanks. I keep forgetting I have this repo on my external, so all I can do here is web edits.
